{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.138.1203.0 (24.11)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"dhora_din\",\"Medidas\",\"fbase_online_pesados_abs_demanda\",\"Arquivo de Amostra\",\"Parâmetro1\",\"Transformar o Arquivo de Exemplo\",\"Transformar Arquivo\",\"fbase_online_pesados_abs_cancelamentos\",\"Arquivo de Amostra (2)\",\"Parâmetro2\",\"Transformar o Arquivo de Exemplo (2)\",\"Transformar Arquivo (2)\",\"Consulta1\",\"dcalendario\",\"fbase_abastecimento_demanda\",\"fbase_abastecimento_cancelamentos\",\"dsetor\",\"fbase_hc_abastecimento\",\"fbase_expedicoes_abs\",\"dhora\",\"dzona\",\"dvalor_monetario\",\"dbox\",\"Arquivo de Amostra (4)\",\"Parâmetro3\",\"Transformar o Arquivo de Exemplo (3)\",\"Transformar Arquivo (4)\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Arquivo de Amostra",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Fonte = SharePoint.Contents(\"https://viavarejo.sharepoint.com/sites/grupo_de_dados_wave\", [ApiVersion = 15]),",
          "    #\"Atualizaes de Relatrios Gerais\" = Fonte{[Name=\"Atualizaes de Relatrios Gerais\"]}[Content],",
          "    #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\" = #\"Atualizaes de Relatrios Gerais\"{[Name=\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"]}[Content],",
          "    #\"Relatórios históricos\" = #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"{[Name=\"Relatórios históricos\"]}[Content],",
          "    #\"Painel de Navegacao Gerencial - ADMS - Vinicius &  Almeida\" = #\"Relatórios históricos\"{[Name=\"Painel de Navegacao Gerencial - ADMS - Vinicius &  Almeida\"]}[Content],",
          "    #\"SLA - Leves && Pesados && EAD\" = #\"Painel de Navegacao Gerencial - ADMS - Vinicius &  Almeida\"{[Name=\"SLA - Leves && Pesados && EAD\"]}[Content],",
          "    #\"Demanda All\" = #\"SLA - Leves && Pesados && EAD\"{[Name=\"Demanda All\"]}[Content],",
          "    Navegação1 = #\"Demanda All\"{0}[Content]",
          "in",
          "    Navegação1"
        ],
        "kind": "m",
        "lineageTag": "feef2ac3-325f-4b09-8f59-e5df3f6c07af",
        "queryGroup": "Transformar Arquivo de fbase_online_pesados_demanda\\Consultas Auxiliares"
      },
      {
        "name": "Parâmetro1",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Arquivo de Amostra\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Arquivo de Amostra\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "2867a508-aeb9-4aa1-bcc6-8c0d778ad949",
        "queryGroup": "Transformar Arquivo de fbase_online_pesados_demanda\\Consultas Auxiliares"
      },
      {
        "name": "Transformar o Arquivo de Exemplo",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Csv.Document(Parâmetro1,[Delimiter=\"\t\", Columns=31, Encoding=1200, QuoteStyle=QuoteStyle.None]),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
          "in",
          "    #\"Cabeçalhos Promovidos\""
        ],
        "kind": "m",
        "lineageTag": "8a234d44-9fda-4a34-93ff-880f3123ca86",
        "queryGroup": "Transformar Arquivo de fbase_online_pesados_demanda"
      },
      {
        "name": "Transformar Arquivo",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Fonte = (Parâmetro1 as binary) => let",
          "    Fonte = Csv.Document(Parâmetro1,[Delimiter=\"\t\", Columns=31, Encoding=1200, QuoteStyle=QuoteStyle.None]),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
          "in",
          "    #\"Cabeçalhos Promovidos\"",
          "in",
          "    Fonte"
        ],
        "kind": "m",
        "lineageTag": "f98e5337-3dcd-443a-801e-6ef46c3a7ce1",
        "queryGroup": "Transformar Arquivo de fbase_online_pesados_demanda\\Consultas Auxiliares"
      },
      {
        "name": "Arquivo de Amostra (2)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Fonte = SharePoint.Contents(\"https://viavarejo.sharepoint.com/sites/grupo_de_dados_wave\", [ApiVersion = 15]),",
          "    #\"Atualizaes de Relatrios Gerais\" = Fonte{[Name=\"Atualizaes de Relatrios Gerais\"]}[Content],",
          "    #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\" = #\"Atualizaes de Relatrios Gerais\"{[Name=\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"]}[Content],",
          "    #\"Relatórios históricos\" = #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"{[Name=\"Relatórios históricos\"]}[Content],",
          "    #\"Painel de Navegacao Gerencial - ADMS - Vinicius &  Almeida\" = #\"Relatórios históricos\"{[Name=\"Painel de Navegacao Gerencial - ADMS - Vinicius &  Almeida\"]}[Content],",
          "    #\"SLA - Leves && Pesados && EAD\" = #\"Painel de Navegacao Gerencial - ADMS - Vinicius &  Almeida\"{[Name=\"SLA - Leves && Pesados && EAD\"]}[Content],",
          "    #\"Cancelamento All\" = #\"SLA - Leves && Pesados && EAD\"{[Name=\"Cancelamento All\"]}[Content],",
          "    Navegação1 = #\"Cancelamento All\"{0}[Content]",
          "in",
          "    Navegação1"
        ],
        "kind": "m",
        "lineageTag": "a7337b92-4648-430a-823a-538e6bc65bf4",
        "queryGroup": "Transformar Arquivo de Consulta1\\Consultas Auxiliares"
      },
      {
        "name": "Parâmetro2",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Arquivo de Amostra (2)\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Arquivo de Amostra (2)\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "39133742-5bfb-4ef4-88f0-ef58f785f522",
        "queryGroup": "Transformar Arquivo de Consulta1\\Consultas Auxiliares"
      },
      {
        "name": "Transformar o Arquivo de Exemplo (2)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Csv.Document(Parâmetro2,[Delimiter=\"\t\", Columns=17, Encoding=1200, QuoteStyle=QuoteStyle.None]),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
          "in",
          "    #\"Cabeçalhos Promovidos\""
        ],
        "kind": "m",
        "lineageTag": "de8d6c71-5892-4ba1-83a7-07cbdc35def7",
        "queryGroup": "Transformar Arquivo de Consulta1"
      },
      {
        "name": "Transformar Arquivo (2)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Fonte = (Parâmetro2) => let",
          "        Fonte = Csv.Document(Parâmetro2,[Delimiter=\"\t\", Columns=17, Encoding=1200, QuoteStyle=QuoteStyle.None]),",
          "        #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
          "    in",
          "        #\"Cabeçalhos Promovidos\"",
          "in",
          "    Fonte"
        ],
        "kind": "m",
        "lineageTag": "455645b2-64d8-46df-8e90-51003a1608ae",
        "queryGroup": "Transformar Arquivo de Consulta1\\Consultas Auxiliares"
      },
      {
        "name": "Consulta1",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Fonte = List.Dates",
          "in",
          "    Fonte"
        ],
        "kind": "m",
        "lineageTag": "ad0511ee-a594-4749-bfb1-deef04705852"
      },
      {
        "name": "dvalor_monetario",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = SharePoint.Contents(\"https://viavarejo.sharepoint.com/sites/grupo_de_dados_wave\", [ApiVersion = 15]),",
          "    #\"Atualizaes de Relatrios Gerais\" = Fonte{[Name=\"Atualizaes de Relatrios Gerais\"]}[Content],",
          "    #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\" = #\"Atualizaes de Relatrios Gerais\"{[Name=\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"]}[Content],",
          "    #\"Relatórios históricos\" = #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"{[Name=\"Relatórios históricos\"]}[Content],",
          "    #\"Painel de Navegacao Gerencial - ADMS - Vinicius &  Almeida\" = #\"Relatórios históricos\"{[Name=\"Painel de Navegacao Gerencial - ADMS - Vinicius &  Almeida\"]}[Content],",
          "    #\"SLA - Abastecimento de Lojas\" = #\"Painel de Navegacao Gerencial - ADMS - Vinicius &  Almeida\"{[Name=\"SLA - Abastecimento de Lojas\"]}[Content],",
          "    #\"valores xlsx\" = #\"SLA - Abastecimento de Lojas\"{[Name=\"valores.xlsx\"]}[Content],",
          "    #\"Pasta de Trabalho Importada do Excel\" = Excel.Workbook(#\"valores xlsx\"),",
          "    Planilha1_Sheet = #\"Pasta de Trabalho Importada do Excel\"{[Item=\"Planilha1\",Kind=\"Sheet\"]}[Data],",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Planilha1_Sheet, [PromoteAllScalars=true]),",
          "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"SKU\", Int64.Type}, {\"SETOR\", type text}, {\"CUSTO UNIT FORN\", type number}}),",
          "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Tipo Alterado\",{{\"SKU\", \"sku\"}}),",
          "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Colunas Renomeadas\",{\"SETOR\"}),",
          "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"Colunas Removidas\",{{\"CUSTO UNIT FORN\", \"valor_monetario\"}}),",
          "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Colunas Renomeadas1\", {\"sku\"})",
          "in",
          "    #\"Duplicatas Removidas\""
        ],
        "kind": "m",
        "lineageTag": "fa793fd6-e619-4369-b947-507abc2b15ee"
      },
      {
        "name": "Arquivo de Amostra (4)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Fonte = SharePoint.Contents(\"https://viavarejo.sharepoint.com/sites/grupo_de_dados_wave\", [ApiVersion = 15]),",
          "    #\"Atualizaes de Relatrios Gerais\" = Fonte{[Name=\"Atualizaes de Relatrios Gerais\"]}[Content],",
          "    #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\" = #\"Atualizaes de Relatrios Gerais\"{[Name=\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"]}[Content],",
          "    #\"Relatórios históricos\" = #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"{[Name=\"Relatórios históricos\"]}[Content],",
          "    #\"Painel de Navegacao Gerencial - ADMS - Vinicius &  Almeida\" = #\"Relatórios históricos\"{[Name=\"Painel de Navegacao Gerencial - ADMS - Vinicius &  Almeida\"]}[Content],",
          "    #\"SLA - Leves && Pesados && EAD\" = #\"Painel de Navegacao Gerencial - ADMS - Vinicius &  Almeida\"{[Name=\"SLA - Leves && Pesados && EAD\"]}[Content],",
          "    #\"Demanda All\" = #\"SLA - Leves && Pesados && EAD\"{[Name=\"Demanda All\"]}[Content],",
          "    #\"Arquivos Ocultos Filtrados1\" = Table.SelectRows(#\"Demanda All\", each [Attributes]?[Hidden]? <> true),",
          "    Navegação1 = #\"Arquivos Ocultos Filtrados1\"{0}[Content]",
          "in",
          "    Navegação1"
        ],
        "kind": "m",
        "lineageTag": "5f4eef7a-ae80-433f-8e29-eaf9720101aa",
        "queryGroup": "Transformar Arquivo de fbase_online_pesados_abs_demanda (2)\\Consultas Auxiliares"
      },
      {
        "name": "Parâmetro3",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Arquivo de Amostra (4)\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Arquivo de Amostra (4)\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "65daacb9-b9ce-4125-8b5f-e9bb5dc83b24",
        "queryGroup": "Transformar Arquivo de fbase_online_pesados_abs_demanda (2)\\Consultas Auxiliares"
      },
      {
        "name": "Transformar o Arquivo de Exemplo (3)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Csv.Document(Parâmetro3,[Delimiter=\"\t\", Columns=31, Encoding=1200, QuoteStyle=QuoteStyle.None]),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
          "in",
          "    #\"Cabeçalhos Promovidos\""
        ],
        "kind": "m",
        "lineageTag": "37026eec-40ea-4ffe-ac00-5547de110255",
        "queryGroup": "Transformar Arquivo de fbase_online_pesados_abs_demanda (2)"
      },
      {
        "name": "Transformar Arquivo (4)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Fonte = (Parâmetro3 as binary) => let",
          "    Fonte = Csv.Document(Parâmetro3,[Delimiter=\"\t\", Columns=31, Encoding=1200, QuoteStyle=QuoteStyle.None]),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
          "in",
          "    #\"Cabeçalhos Promovidos\"",
          "in",
          "    Fonte"
        ],
        "kind": "m",
        "lineageTag": "8c46858f-5c97-41d3-80f2-a47ba480b391",
        "mAttributes": "[ FunctionQueryBinding = \"{\"\"exemplarFormulaName\"\":\"\"Transformar o Arquivo de Exemplo (3)\"\"}\" ]",
        "queryGroup": "Transformar Arquivo de fbase_online_pesados_abs_demanda (2)\\Consultas Auxiliares"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transformar Arquivo de fbase_online_pesados_demanda"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transformar Arquivo de fbase_online_pesados_demanda\\Consultas Auxiliares"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "Transformar Arquivo de Consulta1"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transformar Arquivo de Consulta1\\Consultas Auxiliares"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "4"
          }
        ],
        "folder": "Transformar Arquivo de fbase_online_pesados_abs_demanda (2)"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transformar Arquivo de fbase_online_pesados_abs_demanda (2)\\Consultas Auxiliares"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "6"
          }
        ],
        "folder": "Transformar Arquivo de fbase_online_pesados_abs_demanda (3)"
      }
    ],
    "relationships": [
      {
        "name": "9572b465-d5dd-62a4-7596-8617e6d58df1",
        "fromColumn": "data",
        "fromTable": "fbase_abastecimento_demanda",
        "toColumn": "calendario",
        "toTable": "dcalendario"
      },
      {
        "name": "f43960d4-9ba1-8e99-e85d-aaef248a2719",
        "fromColumn": "data",
        "fromTable": "fbase_abastecimento_cancelamentos",
        "toColumn": "calendario",
        "toTable": "dcalendario"
      },
      {
        "name": "affe8252-f698-be76-c13f-8a5653aa1326",
        "fromColumn": "data",
        "fromTable": "fbase_online_pesados_abs_cancelamentos",
        "toColumn": "calendario",
        "toTable": "dcalendario"
      },
      {
        "name": "b913a9dd-a3d3-52ca-d3df-c683fae6b24a",
        "fromColumn": "data",
        "fromTable": "fbase_online_pesados_abs_demanda",
        "toColumn": "calendario",
        "toTable": "dcalendario"
      },
      {
        "name": "35a936f1-ec45-ad21-84b7-c6d04403aa64",
        "fromColumn": "data",
        "fromTable": "fbase_hc_abastecimento",
        "toColumn": "calendario",
        "toTable": "dcalendario"
      },
      {
        "name": "3bd66bf7-83a5-5725-4a0c-40ce73328528",
        "fromColumn": "sep_setor",
        "fromTable": "fbase_online_pesados_abs_cancelamentos",
        "toColumn": "sep_setor",
        "toTable": "dsetor"
      },
      {
        "name": "72d03876-8cac-d5d7-0586-3b972c4c70da",
        "fromColumn": "data",
        "fromTable": "fbase_expedicoes_abs",
        "toColumn": "calendario",
        "toTable": "dcalendario"
      },
      {
        "name": "e0a80c77-662e-c1df-f8cb-77053701fe0d",
        "fromColumn": "box",
        "fromTable": "fbase_online_pesados_abs_demanda",
        "toColumn": "box",
        "toTable": "dbox"
      },
      {
        "name": "41944f86-a48b-9daf-2854-fe08efdbb2e0",
        "fromColumn": "local_de_picking",
        "fromTable": "fbase_online_pesados_abs_demanda",
        "toColumn": "local",
        "toTable": "dzona"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "dhora_din",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "hora",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "e835b6e8-0a92-4738-bcba-c4c2abc44ea6",
            "sourceColumn": "hora",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d36ca822-6c0d-40ff-be9a-92d6ae71e7c0",
        "partitions": [
          {
            "name": "dhora_din",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Time.From(DateTime.LocalNow()) - #duration(0, 3, 0, 0),",
                "    #\"Convertido para Tabela\" = #table(1, {{Fonte}}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Convertido para Tabela\",{{\"Column1\", \"hora\"}}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Colunas Renomeadas\",{{\"hora\", type time}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Medidas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Coluna 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "displayFolder": "Outros",
            "isHidden": true,
            "lineageTag": "e74c869a-4bf5-47bb-8ab3-870567adc6ff",
            "sourceColumn": "Coluna 1",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "5a25b275-a9d4-4792-ac46-d9ac19709c83",
        "measures": [
          {
            "name": "Current_times",
            "displayFolder": "Outros",
            "expression": [
              "",
              "CONCATENATE(\"Última Atualização 🕐\",FORMAT(SELECTEDVALUE(dhora_din[hora]),\"HH:MM\") )"
            ],
            "lineageTag": "63b4c79a-7da9-429b-8dfb-6b4bfaffa2ef"
          },
          {
            "name": "username",
            "displayFolder": "Outros",
            "expression": [
              "",
              "VAR UsuarioCompleto = USERPRINCIPALNAME()",
              "VAR UsuarioSemDominio = LEFT(UsuarioCompleto, SEARCH(\"@\", UsuarioCompleto, 1) - 1)",
              "VAR UsuarioComEspacos = SUBSTITUTE(UsuarioSemDominio, \".\", \" \")",
              "VAR PrimeiroNome = ",
              "    LEFT(",
              "        UsuarioComEspacos,",
              "        SEARCH(\" \", UsuarioComEspacos & \" \", 1) - 1",
              "    )",
              "VAR nome = ",
              "    UPPER(LEFT(PrimeiroNome, 1)) & LOWER(MID(PrimeiroNome, 2, LEN(PrimeiroNome)))",
              "",
              "",
              "VAR hora = HOUR(NOW() - TIME(3,0,0))",
              "",
              "VAR data = ",
              "",
              "SWITCH(",
              "    TRUE(),",
              "    hora >= 5 && hora <= 12, \"☀️Bom dia, \",",
              "    hora >= 13 && hora <= 18, \"🌤️Boa tarde, \",",
              "    (hora >= 19 && hora <= 23) || (hora >= 0 && hora <= 4), \"🌙Boa noite, \"",
              ")",
              "",
              "    ",
              "",
              "RETURN data & nome"
            ],
            "lineageTag": "dbb94d45-7d26-4416-9930-4807e237749c"
          },
          {
            "name": "hora",
            "displayFolder": "Outros",
            "expression": "CONCATENATE(\"Horário: \",FORMAT(TIME(HOUR(NOW()),MINUTE(NOW()),0) - TIME(3,0,0),\"HH:MM\"))",
            "lineageTag": "dd911c1f-79a0-4f69-ac4f-e9cc892dd105"
          },
          {
            "name": "username2",
            "displayFolder": "Outros",
            "expression": [
              "",
              "VAR UsuarioCompleto = USERPRINCIPALNAME()",
              "VAR UsuarioSemDominio = LEFT(UsuarioCompleto, SEARCH(\"@\", UsuarioCompleto, 1) - 1)",
              "VAR UsuarioComEspacos = SUBSTITUTE(UsuarioSemDominio, \".\", \" \")",
              "",
              "VAR PalavrasSeparadas = SUBSTITUTE(UsuarioComEspacos, \" \", \"|\")",
              "VAR ListaPalavras = ",
              "    ADDCOLUMNS(",
              "        GENERATESERIES(1, PATHLENGTH(PalavrasSeparadas)),",
              "        \"Palavra\", PATHITEM(PalavrasSeparadas, [Value])",
              "    )",
              "VAR NomeCapitalizado = ",
              "    CONCATENATEX(",
              "        ListaPalavras,",
              "        UPPER(LEFT([Palavra], 1)) & LOWER(MID([Palavra], 2, LEN([Palavra]))),",
              "        \" \"",
              "    )",
              "RETURN NomeCapitalizado",
              ""
            ],
            "lineageTag": "2c0321f4-6fc7-48cc-b77b-0d1fbea465ff"
          },
          {
            "name": "sla_abs_tratado",
            "displayFolder": "Info.Abastecimento",
            "expression": [
              "",
              "",
              "VAR A = ",
              "IF(",
              "    NOT(ISFILTERED(dcalendario[nome_mes])),",
              "CALCULATE(",
              "VALUES(dcalendario[nome_mes]),",
              "dcalendario[ano] = YEAR(NOW()) && dcalendario[mes] = MONTH(NOW())),",
              "VALUES(dcalendario[nome_mes]))",
              "",
              "VAR a_tratado = UPPER(LEFT(A,1))&LOWER(MID(A,2,LEN(A)))",
              "",
              "VAR B =",
              "\" SLA - \"&",
              "FORMAT(",
              "IF(",
              "    NOT(ISFILTERED(dcalendario[nome_mes])),",
              "CALCULATE(",
              "1 - DIVIDE([rejeitados_abs],[demanda_geral_abs]),",
              "dcalendario[ano] = YEAR(NOW()) && dcalendario[mes] = MONTH(NOW())),",
              "1 - DIVIDE([rejeitados_abs],[demanda_geral_abs])),\"0.00%\")",
              "",
              "RETURN a_tratado&B",
              ""
            ],
            "lineageTag": "35af57d6-bc2f-44a3-b148-4451ce5444ab"
          },
          {
            "name": "demanda_geral_abs",
            "displayFolder": "Info.Abastecimento",
            "expression": "SUM(fbase_abastecimento_demanda[balanco])+SUM(fbase_abastecimento_demanda[demanda])",
            "formatString": "#,0",
            "lineageTag": "e219266e-8ca7-43df-b6fe-8f42a03057c8"
          },
          {
            "name": "rejeitados_abs",
            "displayFolder": "Info.Abastecimento",
            "expression": "SUM(fbase_abastecimento_demanda[rejeitados_dec])",
            "formatString": "#,0",
            "lineageTag": "84a0e0fa-c118-4018-b854-74b5de1d67cc"
          },
          {
            "name": "teste",
            "displayFolder": "Outros",
            "expression": [
              "",
              "",
              "VALUES(fbase_online_pesados_abs_demanda[setor])"
            ],
            "lineageTag": "e142528d-ee09-431c-a2d8-7afc12c3387b"
          },
          {
            "name": "demanda_entrega_cliente",
            "displayFolder": "Entrega Cliente",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(fbase_online_pesados_abs_demanda[qtd_pecas]),",
              "    fbase_online_pesados_abs_demanda[sep_setor] = \"Entrega a Clientes\") "
            ],
            "formatString": "#,0",
            "lineageTag": "be194103-bd25-48cb-a590-642f9426cfce"
          },
          {
            "name": "entrega_cliente_s01",
            "displayFolder": "Entrega Cliente",
            "expression": [
              "",
              "CALCULATE([demanda_entrega_cliente],",
              "fbase_online_pesados_abs_demanda[tipo_pedido] = \"S01\")"
            ],
            "formatString": "#,0",
            "lineageTag": "7d00b227-6ca1-4b32-b6f9-3553f5edee55"
          },
          {
            "name": "entrega_cliente_s04",
            "displayFolder": "Entrega Cliente",
            "expression": [
              "",
              "CALCULATE([demanda_entrega_cliente],",
              "fbase_online_pesados_abs_demanda[tipo_pedido] = \"S04\")"
            ],
            "formatString": "#,0",
            "lineageTag": "e2f67340-016e-4631-a5f7-2a0dacb7b6ff"
          },
          {
            "name": "black_abs_2024",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Info.Abastecimento",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    [demanda_geral_abs],",
              "    FILTER(",
              "        dcalendario,",
              "        dcalendario[calendario] >= DATE(2024,10,1) &&",
              "        dcalendario[calendario] <= DATE(2024,11,30)))"
            ],
            "formatString": "#,0",
            "lineageTag": "ec92e205-5621-483a-b84d-09d23bdc042a"
          },
          {
            "name": "black_abs_2023",
            "displayFolder": "Info.Abastecimento",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    [demanda_geral_abs],",
              "    FILTER(",
              "        dcalendario,",
              "        dcalendario[calendario] >= DATE(2023,10,1) &&",
              "        dcalendario[calendario] <= DATE(2023,11,30)))"
            ],
            "formatString": "#,0",
            "lineageTag": "263be5e3-bbac-484a-a867-42df33c6b742"
          },
          {
            "name": "48Hrs",
            "displayFolder": "Info.Abastecimento",
            "expression": "SUM(fbase_expedicoes_abs[48hrs])",
            "formatString": "#,0",
            "lineageTag": "2255987a-ccd5-4fda-968b-26b79943c46a"
          },
          {
            "name": "24Hrs",
            "displayFolder": "Info.Abastecimento",
            "expression": "SUM(fbase_expedicoes_abs[24hrs])",
            "formatString": "#,0",
            "lineageTag": "3e727d3c-da9c-4f67-b14e-01da78974b2b"
          },
          {
            "name": "polo",
            "displayFolder": "Info.Abastecimento",
            "expression": "SUM(fbase_expedicoes_abs[polo])",
            "formatString": "#,0",
            "lineageTag": "6423cf56-9623-4bdd-95bb-9f17c9612751"
          },
          {
            "name": "cross",
            "displayFolder": "Info.Abastecimento",
            "expression": "SUM(fbase_expedicoes_abs[crossdocking])",
            "formatString": "#,0",
            "lineageTag": "790c9551-31c3-4f24-881b-17b24de618c8"
          },
          {
            "name": "cancelados_entrega_cliente",
            "displayFolder": "Entrega Cliente",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(fbase_online_pesados_abs_cancelamentos[qtd_pecas]),",
              "    fbase_online_pesados_abs_cancelamentos[sep_setor] = \"entrega a clientes\") "
            ],
            "formatString": "0",
            "lineageTag": "a74aecc6-7fe3-44e5-bece-f16ddfe5f0bb"
          },
          {
            "name": "pi_entrega_cliente_tratado",
            "displayFolder": "Entrega Cliente",
            "expression": [
              "",
              "",
              "VAR A = ",
              "IF(",
              "    NOT(ISFILTERED(dcalendario[nome_mes])),",
              "CALCULATE(",
              "VALUES(dcalendario[nome_mes]),",
              "dcalendario[ano] = YEAR(NOW()) && dcalendario[mes] = MONTH(NOW())),",
              "VALUES(dcalendario[nome_mes]))",
              "",
              "VAR a_tratado = UPPER(LEFT(A,1))&LOWER(MID(A,2,LEN(A)))",
              "",
              "VAR B =",
              "\" PI - \"&",
              "FORMAT(",
              "IF(",
              "    NOT(ISFILTERED(dcalendario[nome_mes])),",
              "CALCULATE(",
              "1 - DIVIDE([cancelados_entrega_cliente],[demanda_entrega_cliente]),",
              "dcalendario[ano] = YEAR(NOW()) && dcalendario[mes] = MONTH(NOW())),",
              "1 - DIVIDE([cancelados_entrega_cliente],[demanda_entrega_cliente])),\"0.00%\")",
              "",
              "RETURN a_tratado&B"
            ],
            "lineageTag": "fb2abcaf-1332-4517-ab81-abbc9407a7e6"
          },
          {
            "name": "demanda_ead",
            "displayFolder": "EAD",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(fbase_online_pesados_abs_demanda[qtd_pecas]),",
              "    fbase_online_pesados_abs_demanda[sep_setor] = \"EAD\") "
            ],
            "formatString": "#,0",
            "lineageTag": "66f225e4-8bbc-42ff-93b9-bbcdb4e0c2b6"
          },
          {
            "name": "cancelados_ead",
            "displayFolder": "EAD",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(fbase_online_pesados_abs_cancelamentos[qtd_pecas]),",
              "    fbase_online_pesados_abs_cancelamentos[sep_setor] = \"EAD\")"
            ],
            "formatString": "#,0",
            "lineageTag": "3e0c3693-9905-45b4-a336-0516fb44d400"
          },
          {
            "name": "pi_entrega_ead",
            "displayFolder": "EAD",
            "expression": [
              "",
              "",
              "VAR A = ",
              "IF(",
              "    NOT(ISFILTERED(dcalendario[nome_mes])),",
              "CALCULATE(",
              "VALUES(dcalendario[nome_mes]),",
              "dcalendario[ano] = YEAR(NOW()) && dcalendario[mes] = MONTH(NOW())),",
              "VALUES(dcalendario[nome_mes]))",
              "",
              "VAR a_tratado = UPPER(LEFT(A,1))&LOWER(MID(A,2,LEN(A)))",
              "",
              "VAR B =",
              "\" PI - \"&",
              "FORMAT(",
              "IF(",
              "    NOT(ISFILTERED(dcalendario[nome_mes])),",
              "CALCULATE(",
              "1 - DIVIDE([cancelados_ead],[demanda_ead]),",
              "dcalendario[ano] = YEAR(NOW()) && dcalendario[mes] = MONTH(NOW())),",
              "1 - DIVIDE([cancelados_ead],[demanda_ead])),\"0.00%\")",
              "",
              "RETURN a_tratado&B"
            ],
            "lineageTag": "d9c88c4a-93ad-49eb-b666-c0b97b015314"
          },
          {
            "name": "demanda_on",
            "displayFolder": "Online",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(fbase_online_pesados_abs_demanda[qtd_pecas]),",
              "    fbase_online_pesados_abs_demanda[sep_setor] = \"leves\") "
            ],
            "formatString": "#,0",
            "lineageTag": "134b1a4c-3b83-4d71-8872-a9d44ed65d00"
          },
          {
            "name": "cancelados_on",
            "displayFolder": "Online",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(fbase_online_pesados_abs_cancelamentos[qtd_pecas]),",
              "    fbase_online_pesados_abs_cancelamentos[sep_setor] = \"leves\")"
            ],
            "formatString": "#,0",
            "lineageTag": "cbedc5d8-655e-42dc-872c-7b3b4be23a38"
          },
          {
            "name": "pi_online_tratado",
            "displayFolder": "Online",
            "expression": [
              "",
              "",
              "VAR A = ",
              "IF(",
              "    NOT(ISFILTERED(dcalendario[nome_mes])),",
              "CALCULATE(",
              "VALUES(dcalendario[nome_mes]),",
              "dcalendario[ano] = YEAR(NOW()) && dcalendario[mes] = MONTH(NOW())),",
              "VALUES(dcalendario[nome_mes]))",
              "",
              "VAR a_tratado = UPPER(LEFT(A,1))&LOWER(MID(A,2,LEN(A)))",
              "",
              "VAR B =",
              "\" PI - \"&",
              "FORMAT(",
              "IF(",
              "    NOT(ISFILTERED(dcalendario[nome_mes])),",
              "CALCULATE(",
              "1 - DIVIDE([cancelados_on],[demanda_on]),",
              "dcalendario[ano] = YEAR(NOW()) && dcalendario[mes] = MONTH(NOW())),",
              "1 - DIVIDE([cancelados_on],[demanda_on])),\"0.00%\")",
              "",
              "RETURN a_tratado&B"
            ],
            "lineageTag": "392e57d9-6b1e-4e11-9679-eaecbb09852f"
          },
          {
            "name": "black_entrega_clientes_2024",
            "displayFolder": "Entrega Cliente",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    [demanda_entrega_cliente],",
              "    FILTER(",
              "        dcalendario,",
              "        dcalendario[calendario] >= DATE(2024,11,1) &&",
              "        dcalendario[calendario] <= DATE(2024,11,30)))"
            ],
            "formatString": "#,0",
            "lineageTag": "53612fc0-06d2-4442-9e6a-fc552c0a8d59"
          },
          {
            "name": "texto_black_friday",
            "displayFolder": "Outros",
            "expression": "\"BF\"",
            "lineageTag": "21a5c3ce-6d07-4df7-b1eb-028803e7df69"
          },
          {
            "name": "black_ead_2024",
            "displayFolder": "EAD",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    [demanda_ead],",
              "    FILTER(",
              "        dcalendario,",
              "        dcalendario[calendario] >= DATE(2024,11,1) &&",
              "        dcalendario[calendario] <= DATE(2024,11,30)))"
            ],
            "formatString": "#,0",
            "lineageTag": "21cc73b9-74ad-4c1d-a6ad-24635cf9455a"
          },
          {
            "name": "black_on_2024",
            "displayFolder": "Online",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    [demanda_on],",
              "    FILTER(",
              "        dcalendario,",
              "        dcalendario[calendario] >= DATE(2024,11,1) &&",
              "        dcalendario[calendario] <= DATE(2024,11,30)))"
            ],
            "formatString": "#,0",
            "lineageTag": "77f565d6-2cb9-4150-9dd9-73e54404eff7"
          },
          {
            "name": "demanda_abs_olpn",
            "displayFolder": "Info.Abastecimento",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(fbase_online_pesados_abs_demanda[qtd_pecas]),",
              "    dsetor[sep_setor] = \"Abastecimento de lojas\")"
            ],
            "formatString": "#,0",
            "lineageTag": "fa0e80cd-0759-4ed6-9bea-7fb7ca9e0e0b"
          },
          {
            "name": "mes_atual",
            "displayFolder": "Info.Geral",
            "expression": [
              "",
              "UPPER(LEFT(FORMAT(TODAY(), \"MMMM\"), 1)) & MID(FORMAT(TODAY(), \"MMMM\"), 2, LEN(FORMAT(TODAY(), \"MMMM\")))",
              "",
              ""
            ],
            "lineageTag": "e0c18f1b-922d-4fe3-9d17-483d2ab003ab"
          },
          {
            "name": "mes_passado",
            "displayFolder": "Info.Geral",
            "expression": [
              "UPPER(LEFT(FORMAT(EDATE(TODAY(), -1), \"MMMM\"), 1)) & MID(FORMAT(EDATE(TODAY(), -1), \"MMMM\"), 2, LEN(FORMAT(EDATE(TODAY(), -1), \"MMMM\")))",
              ""
            ],
            "lineageTag": "4c95b173-f1bb-40b4-b917-23444ec4ece7"
          },
          {
            "name": "mes_tratado",
            "displayFolder": "Info.Geral",
            "expression": [
              "",
              "",
              "VAR A = SELECTEDVALUE(dcalendario[nome_mes])",
              "",
              "VAR B = UPPER(LEFT(A,1))&LOWER(MID(A,2,LEN(A)))",
              "",
              "RETURN B"
            ],
            "lineageTag": "fedad70c-bc0b-4b40-a9cc-f8e65fc40700"
          },
          {
            "name": "dia_tratado",
            "displayFolder": "Info.Geral",
            "expression": [
              "",
              "",
              "VAR A = SELECTEDVALUE(dcalendario[nome_dia])",
              "",
              "VAR B = UPPER(LEFT(A,1))&LOWER(MID(A,2,LEN(A)))",
              "",
              "RETURN B"
            ],
            "lineageTag": "2791c19f-cf34-4596-bb9d-acc10b5e8923"
          },
          {
            "name": "ano_tratado",
            "displayFolder": "Info.Geral",
            "expression": "SELECTEDVALUE(dcalendario[ano])",
            "formatString": "0",
            "lineageTag": "f833ae66-506f-467f-93a2-7c15a87e707c"
          },
          {
            "name": "year_over_year_abs",
            "displayFolder": "Info.Abastecimento",
            "expression": [
              "",
              "CALCULATE(",
              "    [demanda_geral_abs],",
              "    DATEADD(dcalendario[calendario], -1, YEAR))"
            ],
            "formatString": "#,0",
            "lineageTag": "bb6a3d96-3bb1-441d-9411-c3ad1ce1960e"
          },
          {
            "name": "%year_over_year_abs",
            "displayFolder": "Info.Abastecimento",
            "expression": [
              "",
              "",
              "IF(",
              "    [demanda_geral_abs]>[year_over_year_abs],",
              "    FORMAT(1 - DIVIDE([year_over_year_abs],[demanda_geral_abs]),\"0.00%\")&\" ⬆️\",",
              "    FORMAT(DIVIDE([year_over_year_abs],[demanda_geral_abs]) - 1,\"0.00%\")&\" ⬇️\")"
            ],
            "lineageTag": "a1c6b328-56d1-42cc-b1c5-a06b350a943a"
          },
          {
            "name": "month_over_month_abs",
            "displayFolder": "Info.Abastecimento",
            "expression": [
              "",
              "CALCULATE(",
              "    [demanda_geral_abs],",
              "    DATEADD(dcalendario[calendario], -1, MONTH))"
            ],
            "formatString": "#,0",
            "lineageTag": "04f0f2b0-0098-4edd-a6af-6d1bc61bcb12"
          },
          {
            "name": "%month_over_month_abs",
            "displayFolder": "Info.Abastecimento",
            "expression": [
              "",
              "",
              "IF(",
              "    [demanda_geral_abs]>[month_over_month_abs],",
              "    FORMAT(1 - DIVIDE([month_over_month_abs],[demanda_geral_abs]),\"0.00%\")&\" ⬆️\",",
              "    FORMAT(DIVIDE([month_over_month_abs],[demanda_geral_abs]) - 1,\"0.00%\")&\" ⬇️\")"
            ],
            "lineageTag": "13251fed-44b0-453d-adaf-396c2bb1205e"
          },
          {
            "name": "day_over_day_abs",
            "displayFolder": "Info.Abastecimento",
            "expression": [
              "",
              "CALCULATE(",
              "    [demanda_geral_abs],",
              "    DATEADD(dcalendario[calendario], -1, DAY))"
            ],
            "formatString": "#,0",
            "lineageTag": "a5ec4188-2689-4eb8-8569-a1c5caf67548"
          },
          {
            "name": "%day_over_day_abs",
            "displayFolder": "Info.Abastecimento",
            "expression": [
              "",
              "",
              "IF(",
              "    [demanda_geral_abs]>[day_over_day_abs],",
              "    FORMAT(1 - DIVIDE([day_over_day_abs],[demanda_geral_abs]),\"0.00%\")&\" ⬆️\",",
              "    FORMAT(DIVIDE([day_over_day_abs],[demanda_geral_abs]) - 1,\"0.00%\")&\" ⬇️\")"
            ],
            "lineageTag": "82247a7d-83c1-4d0a-970c-5482a373c69c"
          },
          {
            "name": "demanda_pesados",
            "displayFolder": "Pesados",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(fbase_online_pesados_abs_demanda[qtd_pecas]),",
              "    fbase_online_pesados_abs_demanda[sep_setor] = \"Entrega a Clientes\" || fbase_online_pesados_abs_demanda[sep_setor] = \"EAD\") "
            ],
            "formatString": "#,0",
            "lineageTag": "c978aa95-ad1a-4b3d-b8d4-50fdb21a53ad"
          },
          {
            "name": "%_cap_pesados",
            "displayFolder": "Pesados",
            "expression": [
              "",
              "",
              "IF( ",
              "    (SELECTEDVALUE(dcalendario[calendario]) >= DATE(2024,10,1)) && (SELECTEDVALUE(dcalendario[calendario]) <= DATE(2024,12,31)),",
              "    SUM(fbase_online_pesados_abs_demanda[qtd_pecas])/6000,",
              "    SUM(fbase_online_pesados_abs_demanda[qtd_pecas])/3000)",
              "",
              " "
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b46bd144-2f1b-49c2-a35e-fde8eb241e61"
          },
          {
            "name": "%_dia_x_semana",
            "displayFolder": "Pesados",
            "expression": [
              "",
              "",
              "[demanda_pesados]",
              "",
              "/",
              "",
              "CALCULATE(",
              "    [demanda_pesados],",
              "    dcalendario[semana] = SELECTEDVALUE(dcalendario[semana]),",
              "    ALL(dcalendario[dia]))"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "8fb3cea2-9c7a-486b-a274-9f8e83850cdf"
          },
          {
            "name": "TextoFormatado",
            "displayFolder": "Pesados",
            "expression": [
              "",
              "IF(",
              "    [%_cap_pesados] > 1,",
              "    \"<b><span style='color:red'>\" & FORMAT([%_cap_pesados], \"0.00%\") & \"</span></b>\",",
              "    FORMAT([%_cap_pesados], \"0.00%\")",
              ")",
              ""
            ],
            "lineageTag": "ada24f26-0750-41d1-9e3a-541a061048a5"
          },
          {
            "name": "format_fundo",
            "displayFolder": "Pesados",
            "expression": [
              "",
              "",
              "IF([%_cap_pesados] > 1,  \"#EE7F7F\", \"\"",
              ") "
            ],
            "lineageTag": "7a64c298-4011-4a8e-8e16-e7bc2541124e"
          },
          {
            "name": "black_pesados_2024",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Pesados",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    [demanda_pesados],",
              "    FILTER(",
              "        dcalendario,",
              "        dcalendario[calendario] >= DATE(2024,10,1) &&",
              "        dcalendario[calendario] <= DATE(2024,12,31)))"
            ],
            "lineageTag": "56660b81-a598-454d-bf0e-f1e575928e1d"
          },
          {
            "name": "month_over_month_pesados",
            "displayFolder": "Pesados",
            "expression": [
              "",
              "CALCULATE(",
              "    [demanda_pesados],",
              "    DATEADD(dcalendario[calendario], -1, MONTH))"
            ],
            "formatString": "0",
            "lineageTag": "7565839f-c9f4-437e-a0f6-8385d31e4f07"
          },
          {
            "name": "year_over_year_pesados",
            "displayFolder": "Pesados",
            "expression": [
              "",
              "CALCULATE(",
              "    [demanda_pesados],",
              "    DATEADD(dcalendario[calendario], -1, YEAR))"
            ],
            "formatString": "0",
            "lineageTag": "3c139ec9-2034-4958-a9fe-0d9d38634335"
          },
          {
            "name": "day_over_day_pesados",
            "displayFolder": "Pesados",
            "expression": [
              "",
              "CALCULATE(",
              "    [demanda_pesados],",
              "    DATEADD(dcalendario[calendario], -1, DAY))"
            ],
            "formatString": "0",
            "lineageTag": "a34020e0-a0d7-4ea8-bc2e-1f72043c7ebf"
          },
          {
            "name": "%day_over_day_pesados",
            "displayFolder": "Pesados",
            "expression": [
              "",
              "",
              "IF(",
              "    [demanda_pesados]>[day_over_day_pesados],",
              "    FORMAT(1 - DIVIDE([day_over_day_pesados],[demanda_pesados]),\"0.00%\")&\" ⬆️\",",
              "    FORMAT(DIVIDE([day_over_day_pesados],[demanda_pesados]) - 1,\"0.00%\")&\" ⬇️\")"
            ],
            "lineageTag": "c33d917f-a4ad-4752-b4c3-cbfc45594248"
          },
          {
            "name": "%month_over_month_pesados",
            "displayFolder": "Pesados",
            "expression": [
              "",
              "",
              "IF(",
              "    [demanda_pesados]>[month_over_month_pesados],",
              "    FORMAT(1 - DIVIDE([month_over_month_pesados],[demanda_pesados]),\"0.00%\")&\" ⬆️\",",
              "    FORMAT(DIVIDE([month_over_month_pesados],[demanda_pesados]) - 1,\"0.00%\")&\" ⬇️\")"
            ],
            "lineageTag": "acfdf327-0899-45e1-94d3-354fed1dba3a"
          },
          {
            "name": "%year_over_year_pesados",
            "displayFolder": "Pesados",
            "expression": [
              "",
              "",
              "IF(",
              "    [demanda_pesados]>[year_over_year_pesados],",
              "    FORMAT(1 - DIVIDE([year_over_year_pesados],[demanda_pesados]),\"0.00%\")&\" ⬆️\",",
              "    FORMAT(DIVIDE([year_over_year_pesados],[demanda_pesados]) - 1,\"0.00%\")&\" ⬇️\")"
            ],
            "lineageTag": "734665c8-18a8-4823-897c-78f4406db59f"
          },
          {
            "name": "%_box",
            "displayFolder": "Pesados",
            "expression": [
              "",
              "",
              "[vol_pesados]",
              "/SELECTEDVALUE(dbox[cubage_m3])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d1e48b84-8bd4-4a90-8b33-5ea6d6f4c871"
          },
          {
            "name": "data_selecionada",
            "displayFolder": "Pesados",
            "expression": [
              "",
              "",
              "VAR dia = ",
              "",
              "IF(",
              "    NOT(ISFILTERED(dcalendario[dia])),",
              "    \"\",",
              "    SELECTEDVALUE(dcalendario[dia]))",
              "",
              "VAR mes = ",
              "",
              "IF(",
              "    NOT(ISFILTERED(dcalendario[nome_mes])),",
              "    \"\",",
              "    SELECTEDVALUE(dcalendario[nome_mes]))",
              "",
              "VAR ano = ",
              "",
              "IF(",
              "    NOT(ISFILTERED(dcalendario[ano])),",
              "    \"\",",
              "    SELECTEDVALUE(dcalendario[ano]))",
              "",
              "RETURN",
              "IF(",
              "    NOT(ISFILTERED(dcalendario)),",
              "    \"Considerando o período completo\",",
              "dia&\" \"&mes&\" \"&ano)"
            ],
            "lineageTag": "2b7d384b-b816-4c11-8f89-5c07a6d5e278"
          },
          {
            "name": "data_selecionada_qtd_pesados",
            "displayFolder": "Pesados",
            "expression": [
              "",
              "",
              "IF(",
              "    SELECTEDVALUE(dcalendario[calendario]) = TODAY(),",
              "    CALCULATE(",
              "        [demanda_pesados],",
              "        fbase_online_pesados_abs_demanda[Status oLPN] <> \"Shipped\" ),",
              "        [demanda_pesados])"
            ],
            "formatString": "0",
            "lineageTag": "bdc17fa9-5a5d-4df6-bf71-3d3737796c61"
          },
          {
            "name": "format_fundov2",
            "displayFolder": "Pesados",
            "expression": [
              "",
              "",
              "IF([%_box] > 1,  \"#EE7F7F\", \"\"",
              ") "
            ],
            "lineageTag": "c2b22210-28f1-4a11-aabe-81411782e292"
          },
          {
            "name": "vol_pesados",
            "displayFolder": "Pesados",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    SUM(fbase_online_pesados_abs_demanda[Volume]),",
              "        fbase_online_pesados_abs_demanda[sep_setor] = \"Entrega a Clientes\" || fbase_online_pesados_abs_demanda[sep_setor] = \"EAD\") "
            ],
            "formatString": "0.00",
            "lineageTag": "16a7ba53-1e63-43f8-bf7c-28598c62f877"
          },
          {
            "name": "valor_monetario",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-BR\"}"
              }
            ],
            "displayFolder": "Pesados",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    SUM(fbase_online_pesados_abs_demanda[valor_monetario]),",
              "    fbase_online_pesados_abs_demanda[sep_setor] = \"Entrega a Clientes\" || fbase_online_pesados_abs_demanda[sep_setor] = \"EAD\")"
            ],
            "formatString": "\"R$\"#,0.00;-\"R$\"#,0.00;\"R$\"#,0.00",
            "lineageTag": "bb1421ac-4621-4be4-9c37-0c9fed9e8caa"
          },
          {
            "name": "valor_pesados_hj",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-BR\"}"
              }
            ],
            "displayFolder": "Pesados",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    [valor_monetario],",
              "    DATEADD(dcalendario[calendario], 0, DAY),",
              "    fbase_online_pesados_abs_demanda[Status oLPN] <> \"Shipped\")",
              ""
            ],
            "formatString": "\"R$\"#,0.00;-\"R$\"#,0.00;\"R$\"#,0.00",
            "lineageTag": "b474d135-b7d5-4346-9522-e43bb812d0a0"
          },
          {
            "name": "valor_pesados_ontem",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-BR\"}"
              }
            ],
            "displayFolder": "Pesados",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    [valor_monetario],",
              "    DATEADD(dcalendario[calendario], -1, DAY))"
            ],
            "formatString": "\"R$\"#,0.00;-\"R$\"#,0.00;\"R$\"#,0.00",
            "lineageTag": "56e27e22-834f-426b-8877-a03c827dca8f"
          },
          {
            "name": "comp_valor_pesados",
            "displayFolder": "Pesados",
            "expression": [
              "",
              "",
              "VAR A = ",
              "IF([valor_pesados_hj]>[valor_pesados_ontem],",
              "\"⬆️\",\"⬇️\")",
              "",
              "VAR B = ",
              "[valor_pesados_hj]/[valor_pesados_ontem]",
              "",
              "RETURN",
              "FORMAT(B,\"0.00%\")&\" \"&A"
            ],
            "lineageTag": "85ee28b4-0a29-45ef-9b5a-a9cc3655140c"
          },
          {
            "name": "titulo_valor_din",
            "displayFolder": "Pesados",
            "expression": [
              "",
              "",
              "IF([valor_pesados_hj]>[valor_pesados_ontem],\"Superior⬆️\",\"Inferior⬇️\")",
              ""
            ],
            "lineageTag": "b643dcbc-b765-4382-ba0a-160f84b34584"
          },
          {
            "name": "MoM_pesados",
            "displayFolder": "Pesados",
            "expression": [
              "",
              "[month_over_month_pesados]&\" | \"&[%month_over_month_pesados]"
            ],
            "lineageTag": "e44f2607-cef7-4b46-ae29-77c3e4c2d80e"
          },
          {
            "name": "YoY_pesados",
            "displayFolder": "Pesados",
            "expression": [
              "",
              "",
              "[year_over_year_pesados]&\" | \"&[%year_over_year_pesados]"
            ],
            "lineageTag": "a35f436f-f539-45ab-85bd-54a6708a7203"
          },
          {
            "name": "DoD_pesados",
            "displayFolder": "Pesados",
            "expression": [
              "",
              "",
              "[day_over_day_pesados]&\" | \"&[%day_over_day_pesados]"
            ],
            "lineageTag": "312d31d6-61a1-485b-a087-18cd09045438"
          },
          {
            "name": "day_over_day_pesados_monetario",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-BR\"}"
              }
            ],
            "displayFolder": "Pesados",
            "expression": [
              "",
              "CALCULATE(",
              "    [valor_monetario],",
              "    DATEADD(dcalendario[calendario], -1, DAY))"
            ],
            "formatString": "\"R$\"#,0.00;-\"R$\"#,0.00;\"R$\"#,0.00",
            "lineageTag": "ddd9c8c2-8e90-475f-84b2-f1c9ecfb6f82"
          },
          {
            "name": "%day_over_day_pesados_monetario",
            "displayFolder": "Pesados",
            "expression": [
              "",
              "",
              "IF(",
              "    [valor_monetario]>[day_over_day_pesados_monetario],",
              "    FORMAT(1 - DIVIDE([day_over_day_pesados_monetario],[valor_monetario]),\"0.00%\")&\" ⬆️\",",
              "    FORMAT(DIVIDE([day_over_day_pesados_monetario],[valor_monetario]) - 1,\"0.00%\")&\" ⬇️\")"
            ],
            "lineageTag": "6e54d71e-fc2d-44e3-b8b6-7ea932060720"
          },
          {
            "name": "DoD_pesados_monetario",
            "displayFolder": "Pesados",
            "expression": [
              "",
              "",
              "FORMAT([day_over_day_pesados_monetario], \"R$ #,##0.00\") &\" | \"&[%day_over_day_pesados_monetario]"
            ],
            "lineageTag": "d6a1dc3a-3915-454d-8713-e5cb460b0366"
          },
          {
            "name": "month_over_month_pesados_monetario",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Pesados",
            "expression": [
              "",
              "CALCULATE(",
              "    [valor_monetario],",
              "    DATEADD(dcalendario[calendario], -1, MONTH))"
            ],
            "lineageTag": "9450549c-c6a5-4fea-9f62-68f48183a47c"
          },
          {
            "name": "%month_over_month_pesados_monetario",
            "displayFolder": "Pesados",
            "expression": [
              "",
              "",
              "IF(",
              "    [valor_monetario]>[month_over_month_pesados_monetario],",
              "    FORMAT(1 - DIVIDE([month_over_month_pesados_monetario],[valor_monetario]),\"0.00%\")&\" ⬆️\",",
              "    FORMAT(DIVIDE([month_over_month_pesados_monetario],[valor_monetario]) - 1,\"0.00%\")&\" ⬇️\")"
            ],
            "lineageTag": "1eb62188-8663-4cc5-847e-280bb78d5eb2"
          },
          {
            "name": "MoM_pesados_monetario",
            "displayFolder": "Pesados",
            "expression": [
              "",
              "",
              "FORMAT([month_over_month_pesados_monetario], \"R$ #,##0.00\") &\" | \"&[%month_over_month_pesados_monetario]"
            ],
            "lineageTag": "0f6e3984-a9ca-4759-9d1d-eb93b22d4fc5"
          },
          {
            "name": "year_over_year_pesados_monetario",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Pesados",
            "expression": [
              "",
              "CALCULATE(",
              "    [valor_monetario],",
              "    DATEADD(dcalendario[calendario], -1, YEAR))"
            ],
            "lineageTag": "7c2b64f2-c52d-40e2-a440-9a994cdd6f04"
          },
          {
            "name": "%year_over_year_pesados_monetario",
            "displayFolder": "Pesados",
            "expression": [
              "",
              "",
              "IF(",
              "    [valor_monetario]>[year_over_year_pesados_monetario],",
              "    FORMAT(1 - DIVIDE([year_over_year_pesados_monetario],[valor_monetario]),\"0.00%\")&\" ⬆️\",",
              "    FORMAT(DIVIDE([year_over_year_pesados_monetario],[valor_monetario]) - 1,\"0.00%\")&\" ⬇️\")"
            ],
            "lineageTag": "be251f68-8d5c-4631-b013-d94028fe6b64"
          },
          {
            "name": "YoY_pesados_monetario",
            "displayFolder": "Pesados",
            "expression": [
              "",
              "",
              "FORMAT([year_over_year_pesados_monetario], \"R$ #,##0.00\") &\" | \"&[%year_over_year_pesados_monetario]"
            ],
            "lineageTag": "0e7b5060-53a9-4244-8995-cba7c7892b36"
          },
          {
            "name": "boxs_pesados_entrega_cliente",
            "displayFolder": "Pesados",
            "expression": [
              "",
              "",
              "VAR A = ",
              "CALCULATE(",
              "DISTINCTCOUNT(fbase_online_pesados_abs_demanda[box]),",
              "fbase_online_pesados_abs_demanda[sep_setor] = \"Entrega a Clientes\")",
              "",
              "VAR B = ",
              "CALCULATE(",
              "   SUM(fbase_online_pesados_abs_demanda[Volume]),",
              "    fbase_online_pesados_abs_demanda[sep_setor] = \"Entrega a Clientes\")",
              "",
              "VAR C = ",
              "A/2",
              "",
              "RETURN",
              "\"Porta: \"&FORMAT(C,\"0\")&\" Box: \"&A&\" | \"&FORMAT(B,\"0.00\")&\" M³\"",
              ""
            ],
            "lineageTag": "c9059389-66fd-4025-945b-c48bbbb760b7"
          },
          {
            "name": "boxs_pesados_ead",
            "displayFolder": "Pesados",
            "expression": [
              "",
              "",
              "VAR A = ",
              "CALCULATE(",
              "DISTINCTCOUNT(fbase_online_pesados_abs_demanda[box]),",
              "fbase_online_pesados_abs_demanda[sep_setor] = \"EAD\")",
              "",
              "VAR B = ",
              "CALCULATE(",
              "    SUM(fbase_online_pesados_abs_demanda[Volume]),",
              "    fbase_online_pesados_abs_demanda[sep_setor] = \"EAD\")",
              "",
              "VAR C = ",
              "A/2",
              "",
              "RETURN",
              "\"Porta: \"&FORMAT(C,\"0\")&\" Box: \"&FORMAT(A,\"0\")&\" | \"&FORMAT(B,\"0.00\")&\" M³\""
            ],
            "lineageTag": "0600e5dc-b2b6-4c9f-853b-6a4a3f1651b0"
          },
          {
            "name": "boxs_pesados_geal",
            "displayFolder": "Pesados",
            "expression": [
              "",
              "",
              "VAR A = ",
              "CALCULATE(",
              "DISTINCTCOUNT(fbase_online_pesados_abs_demanda[box]),",
              "fbase_online_pesados_abs_demanda[sep_setor] = \"EAD\" || fbase_online_pesados_abs_demanda[sep_setor] = \"Entrega a Clientes\")",
              "",
              "VAR B = ",
              "CALCULATE(",
              "    [vol_pesados],",
              "    fbase_online_pesados_abs_demanda[sep_setor] = \"EAD\" || fbase_online_pesados_abs_demanda[sep_setor] = \"Entrega a Clientes\")",
              "",
              "VAR C = ",
              "A/2",
              "",
              "RETURN",
              "\"Porta: \"&FORMAT(C,\"0\")&\" Box: \"&A&\" | \"&FORMAT(B,\"0.00\")&\" M³\" "
            ],
            "lineageTag": "da2d0ba0-f131-4b2c-961d-1d28a81b245a"
          },
          {
            "name": "boxs_pesados_fracionado",
            "expression": [
              "",
              "",
              "VAR A = ",
              "CALCULATE(",
              "DISTINCTCOUNT(fbase_online_pesados_abs_demanda[box]),",
              "dbox[desc.1] = \"Fracionado\")",
              "",
              "VAR B = ",
              "CALCULATE(",
              "    SUM(fbase_online_pesados_abs_demanda[Volume]),",
              "    dbox[desc.1] = \"Fracionado\")",
              "",
              "VAR C = ",
              "A/2",
              "",
              "RETURN",
              "\"Porta: \"&FORMAT(C,\"0\")&\" Box: \"&FORMAT(A,\"0\")&\" | \"&FORMAT(B,\"0.00\")&\" M³\""
            ],
            "lineageTag": "7ee7a69c-b8ef-4a93-9178-8e2dacf73d16"
          },
          {
            "name": "boxs_pesados_pp",
            "expression": [
              "",
              "",
              "VAR A = ",
              "CALCULATE(",
              "DISTINCTCOUNT(fbase_online_pesados_abs_demanda[box]),",
              "dbox[desc.1] = \"Porta-Porta 24H - Polo\")",
              "",
              "VAR B = ",
              "CALCULATE(",
              "    SUM(fbase_online_pesados_abs_demanda[Volume]),",
              "    dbox[desc.1] = \"Porta-Porta 24H - Polo\")",
              "",
              "VAR C = ",
              "A/2",
              "",
              "RETURN",
              "\"Porta: \"&FORMAT(C,\"0\")&\" Box: \"&FORMAT(A,\"0\")&\" | \"&FORMAT(B,\"0.00\")&\" M³\""
            ],
            "lineageTag": "ac95309c-4f76-4efc-ada4-02f4ff00bf40"
          },
          {
            "name": "boxs_pesados_ribeirao",
            "expression": [
              "",
              "",
              "VAR A = ",
              "CALCULATE(",
              "DISTINCTCOUNT(fbase_online_pesados_abs_demanda[box]),",
              "dbox[desc.1] = \"Polo Ribeirão Preto\")",
              "",
              "VAR B = ",
              "CALCULATE(",
              "    SUM(fbase_online_pesados_abs_demanda[Volume]),",
              "    dbox[desc.1] = \"Polo Ribeirão Preto\")",
              "",
              "VAR C = ",
              "A/2",
              "",
              "RETURN",
              "\"Porta: \"&FORMAT(C,\"0\")&\" Box: \"&FORMAT(A,\"0\")&\" | \"&FORMAT(B,\"0.00\")&\" M³\""
            ],
            "lineageTag": "138e797d-669b-48b8-871e-3c62ee877053"
          },
          {
            "name": "porta_porta_fixo",
            "expression": [
              "",
              "",
              "VAR A =",
              "CALCULATE(",
              "DISTINCTCOUNT(dbox[box]),",
              "dbox[desc.1] = \"Porta-Porta 24H - Polo\")",
              "",
              "VAR B = ",
              "CALCULATE(",
              "DISTINCTCOUNT(dbox[porta]),",
              "dbox[desc.1] = \"Porta-Porta 24H - Polo\")",
              "",
              "VAR C = ",
              "",
              "CALCULATE(",
              "SUM(dbox[cubage_m3]),",
              "dbox[desc.1] = \"Porta-Porta 24H - Polo\")",
              "",
              "VAR D = ",
              "CALCULATE(",
              "    SUM(fbase_online_pesados_abs_demanda[Volume]),",
              "    dbox[desc.1] = \"Porta-Porta 24H - Polo\")",
              "",
              "VAR E = D/C",
              "",
              "VAR F = ",
              "",
              "IF(E<1, FORMAT(E,\"0.00%\")&\" ⬇️\",FORMAT(E,\"0.00%\")& \" ⬆️\")",
              "",
              "RETURN",
              "",
              "\"Porta: \"&B&\" Box: \"&A&\" | \"&FORMAT(C,\"0\")&\" M³ \"&F"
            ],
            "lineageTag": "1543a9e0-b4ed-4d19-85cb-645d1fb365a4"
          },
          {
            "name": "ribeirao_fixo",
            "expression": [
              "",
              "",
              "VAR A =",
              "CALCULATE(",
              "DISTINCTCOUNT(dbox[box]),",
              "dbox[desc.1] = \"Polo Ribeirão Preto\")",
              "",
              "VAR B = ",
              "CALCULATE(",
              "DISTINCTCOUNT(dbox[porta]),",
              "dbox[desc.1] = \"Polo Ribeirão Preto\")",
              "",
              "VAR C = ",
              "",
              "CALCULATE(",
              "SUM(dbox[cubage_m3]),",
              "dbox[desc.1] = \"Polo Ribeirão Preto\")",
              "",
              "VAR D = ",
              "CALCULATE(",
              "    SUM(fbase_online_pesados_abs_demanda[Volume]),",
              "    dbox[desc.1] = \"Polo Ribeirão Preto\")",
              "",
              "VAR E = D/C",
              "",
              "VAR F = ",
              "",
              "IF(E<1, FORMAT(E,\"0.00%\")&\" ⬇️\",FORMAT(E,\"0.00%\")& \" ⬆️\")",
              "",
              "RETURN",
              "",
              "\"Porta: \"&B&\" Box: \"&A&\" | \"&FORMAT(C,\"0\")&\" M³ \"&F"
            ],
            "lineageTag": "a5f91ae5-2bb7-4106-b1ba-a6ea763165a0"
          },
          {
            "name": "Medida",
            "annotations": [
              {
                "name": "436ba87b-9c83-4389-a31b-ebd06a36be98",
                "value": "{\"Expression\":null}"
              },
              {
                "name": "277cc1b9-af89-4597-8e15-cacc25c0886b",
                "value": "Para usar caracteres especiais em um nome de medida, coloque todo o nome entre colchetes ( [] ) e adicione ] a quaisquer colchetes de fechamento no nome."
              }
            ],
            "lineageTag": "dac198ce-beea-42e5-b284-6dd036bd3173"
          },
          {
            "name": "fracionado",
            "expression": [
              "",
              "",
              "VAR A =",
              "CALCULATE(",
              "DISTINCTCOUNT(dbox[box]),",
              "dbox[desc.1] = \"Fracionado\")",
              "",
              "VAR B = ",
              "CALCULATE(",
              "DISTINCTCOUNT(dbox[porta]),",
              "dbox[desc.1] = \"Fracionado\")",
              "",
              "VAR C = ",
              "",
              "CALCULATE(",
              "SUM(dbox[cubage_m3]),",
              "dbox[desc.1] = \"Fracionado\")",
              "",
              "VAR D = ",
              "CALCULATE(",
              "    SUM(fbase_online_pesados_abs_demanda[Volume]),",
              "    dbox[desc.1] = \"Fracionado\")",
              "",
              "VAR E = D/C",
              "",
              "VAR F = ",
              "",
              "IF(E<1, FORMAT(E,\"0.00%\")&\" ⬇️\",FORMAT(E,\"0.00%\")& \" ⬆️\")",
              "",
              "RETURN",
              "",
              "\"Porta: \"&B&\" Box: \"&A&\" | \"&FORMAT(C,\"0\")&\" M³ \"&F"
            ],
            "lineageTag": "74fb9211-0122-4f3d-b6a0-76c06cb1cdfb"
          },
          {
            "name": "EAD_fixo",
            "expression": [
              "",
              "",
              "VAR A =",
              "CALCULATE(",
              "DISTINCTCOUNT(dbox[box]),",
              "dbox[setor] = \"EAD\")",
              "",
              "VAR B =     ",
              "CALCULATE(",
              "DISTINCTCOUNT(dbox[porta]),",
              "dbox[setor] = \"EAD\")",
              "",
              "VAR C = ",
              "",
              "CALCULATE(",
              "SUM(dbox[cubage_m3]),",
              "dbox[setor] = \"EAD\")",
              "",
              "VAR D = ",
              "CALCULATE(",
              "    SUM(fbase_online_pesados_abs_demanda[Volume]),",
              "    dbox[setor] = \"EAD\")",
              "",
              "VAR E = D/C",
              "",
              "VAR F = ",
              "",
              "IF(E<1, FORMAT(E,\"0.00%\")&\" ⬇️\",FORMAT(E,\"0.00%\")& \" ⬆️\")",
              "",
              "RETURN",
              "",
              "\"Porta: \"&B&\" Box: \"&A&\" | \"&FORMAT(C,\"0\")&\" M³ \"&F"
            ],
            "lineageTag": "e9f3e798-888f-4a6f-9642-0814c86c008a"
          },
          {
            "name": "pesados_fixo",
            "expression": [
              "",
              "",
              "VAR A =",
              "CALCULATE(",
              "DISTINCTCOUNT(dbox[box]),",
              "dbox[setor] = \"Pesados\")",
              "",
              "VAR B =     ",
              "CALCULATE(",
              "DISTINCTCOUNT(dbox[porta]),",
              "dbox[setor] = \"Pesados\")",
              "",
              "VAR C = ",
              "",
              "CALCULATE(",
              "SUM(dbox[cubage_m3]),",
              "dbox[setor] = \"Pesados\")",
              "",
              "VAR D = ",
              "CALCULATE(",
              "    SUM(fbase_online_pesados_abs_demanda[Volume]),",
              "    dbox[setor] = \"Pesados\")",
              "",
              "VAR E = D/C",
              "",
              "VAR F = ",
              "",
              "IF(E<1, FORMAT(E,\"0.00%\")&\" ⬇️\",FORMAT(E,\"0.00%\")& \" ⬆️\")",
              "",
              "RETURN",
              "",
              "\"Porta: \"&B&\" Box: \"&A&\" | \"&FORMAT(C,\"0\")&\" M³ \"&F"
            ],
            "lineageTag": "ada601e0-8a05-423a-b207-5a6db71cb077"
          },
          {
            "name": "pesados_ead_fixo",
            "expression": [
              "",
              "",
              "VAR A =",
              "CALCULATE(",
              "DISTINCTCOUNT(dbox[box]),",
              "dbox[setor] = \"Pesados\" || dbox[setor] = \"EAD\")",
              "",
              "VAR B =     ",
              "CALCULATE(",
              "DISTINCTCOUNT(dbox[porta]),",
              "dbox[setor] = \"Pesados\" || dbox[setor] = \"EAD\")",
              "",
              "VAR C = ",
              "",
              "CALCULATE(",
              "SUM(dbox[cubage_m3]),",
              "dbox[setor] = \"Pesados\" || dbox[setor] = \"EAD\")",
              "",
              "VAR D = ",
              "CALCULATE(",
              "    SUM(fbase_online_pesados_abs_demanda[Volume]),",
              "    dbox[setor] = \"Pesados\" || dbox[setor] = \"EAD\")",
              "",
              "VAR E = D/C",
              "",
              "VAR F = ",
              "",
              "IF(E<1, FORMAT(E,\"0.00%\")&\" ⬇️\",FORMAT(E,\"0.00%\")& \" ⬆️\")",
              "",
              "RETURN",
              "",
              "\"Porta: \"&B&\" Box: \"&A&\" | \"&FORMAT(C,\"0\")&\" M³ \"&F"
            ],
            "lineageTag": "a1979943-00ce-4994-ae33-eb397f516b82"
          }
        ],
        "partitions": [
          {
            "name": "Medidas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Coluna 1\", type text}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fbase_online_pesados_abs_demanda",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "filial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c80fcea7-a38b-4b52-9f18-786176ba57b1",
            "sourceColumn": "filial",
            "summarizeBy": "sum"
          },
          {
            "name": "tipo_pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ba9c09c-d09b-4b79-b835-3bb6cc48872f",
            "sourceColumn": "tipo_pedido",
            "summarizeBy": "none"
          },
          {
            "name": "data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "0eee35b9-911e-45e9-b6e8-22ed3ad8c657",
            "sourceColumn": "data",
            "summarizeBy": "none"
          },
          {
            "name": "qtd_pecas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ef40a554-8d9d-4c8a-8cfc-4510a05d418f",
            "sourceColumn": "qtd_pecas",
            "summarizeBy": "sum"
          },
          {
            "name": "setor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "199d567c-cca6-4e80-a3f0-e696bd2a0cd9",
            "sourceColumn": "setor",
            "summarizeBy": "none"
          },
          {
            "name": "box",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "54c7d925-566e-4bd3-87b3-21bfae5d25d1",
            "sourceColumn": "box",
            "summarizeBy": "none"
          },
          {
            "name": "data_locacao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "dd249760-5857-42b2-88c2-c111ca8dda30",
            "sourceColumn": "data_locacao",
            "summarizeBy": "none"
          },
          {
            "name": "local_de_picking",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "35da482b-ee5a-4930-b377-b4d8b98ede89",
            "sourceColumn": "local_de_picking",
            "summarizeBy": "none"
          },
          {
            "name": "data_limite",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "09ae6fe0-aabb-4c26-a151-59722243d36b",
            "sourceColumn": "data_limite",
            "summarizeBy": "none"
          },
          {
            "name": "sep_setor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a6507119-5313-4be0-9ebe-111d78778e51",
            "sourceColumn": "sep_setor",
            "summarizeBy": "none"
          },
          {
            "name": "salao_or_par",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd2a2944-bb83-46e1-ad48-447961a18c6a",
            "sourceColumn": "salao_or_par",
            "summarizeBy": "none"
          },
          {
            "name": "tipo_expedicao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "65d1ae3b-8dc8-48bf-862f-b15f026f7698",
            "sourceColumn": "tipo_expedicao",
            "summarizeBy": "none"
          },
          {
            "name": "48hrs_24hrs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ecf0b04c-c12c-4f4c-bc06-f7765133bf6f",
            "sourceColumn": "48hrs_24hrs",
            "summarizeBy": "none"
          },
          {
            "name": "Item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "023b0eb0-302c-4159-8087-bafecc3bcd3c",
            "sourceColumn": "Item",
            "summarizeBy": "sum"
          },
          {
            "name": "valor_monetario",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-BR\"}"
              }
            ],
            "dataType": "double",
            "formatString": "\"R$\"#,0.00;-\"R$\"#,0.00;\"R$\"#,0.00",
            "lineageTag": "91a2de51-2cf2-4bef-9f01-36e17e62f4eb",
            "sourceColumn": "valor_monetario",
            "summarizeBy": "sum"
          },
          {
            "name": "setor_tratado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a64b08b4-d415-4389-9eb8-7021e3a8d46f",
            "sourceColumn": "setor_tratado",
            "summarizeBy": "none"
          },
          {
            "name": "Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9001b466-cdf6-49b8-ad14-a604d645f2dc",
            "sourceColumn": "Pedido",
            "summarizeBy": "sum"
          },
          {
            "name": "Volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7992f415-e350-4b7d-9b1b-1a910e2372e1",
            "sourceColumn": "Volume",
            "summarizeBy": "sum"
          },
          {
            "name": "Status oLPN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b67f7a71-cc6e-4ced-bad9-16f25a3cde0e",
            "sourceColumn": "Status oLPN",
            "summarizeBy": "none"
          },
          {
            "name": "Descrição",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1b7f30ef-60bf-46be-8b89-d2c11d8a412a",
            "sourceColumn": "Descrição",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "86f80c0f-1098-475d-857e-3f299ac54dc7",
        "partitions": [
          {
            "name": "fbase_online_pesados_abs_demanda",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = SharePoint.Contents(\"https://viavarejo.sharepoint.com/sites/grupo_de_dados_wave\", [ApiVersion = 15]),",
                "    #\"Atualizaes de Relatrios Gerais\" = Fonte{[Name=\"Atualizaes de Relatrios Gerais\"]}[Content],",
                "    #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\" = #\"Atualizaes de Relatrios Gerais\"{[Name=\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"]}[Content],",
                "    #\"Relatórios históricos\" = #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"{[Name=\"Relatórios históricos\"]}[Content],",
                "    #\"Painel de Navegacao Gerencial - ADMS - Vinicius &  Almeida\" = #\"Relatórios históricos\"{[Name=\"Painel de Navegacao Gerencial - ADMS - Vinicius &  Almeida\"]}[Content],",
                "    #\"SLA - Leves && Pesados && EAD\" = #\"Painel de Navegacao Gerencial - ADMS - Vinicius &  Almeida\"{[Name=\"SLA - Leves && Pesados && EAD\"]}[Content],",
                "    #\"Demanda All\" = #\"SLA - Leves && Pesados && EAD\"{[Name=\"Demanda All\"]}[Content],",
                "    #\"Arquivos Ocultos Filtrados1\" = Table.SelectRows(#\"Demanda All\", each [Attributes]?[Hidden]? <> true),",
                "    #\"Invocar Função Personalizada1\" = Table.AddColumn(#\"Arquivos Ocultos Filtrados1\", \"Transformar Arquivo\", each #\"Transformar Arquivo\"([Content])),",
                "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"Invocar Função Personalizada1\", {\"Name\", \"Nome da Origem\"}),",
                "    #\"Outras Colunas Removidas1\" = Table.SelectColumns(#\"Colunas Renomeadas1\", {\"Nome da Origem\", \"Transformar Arquivo\"}),",
                "    #\"Coluna de Tabela Expandida1\" = Table.ExpandTableColumn(#\"Outras Colunas Removidas1\", \"Transformar Arquivo\", Table.ColumnNames(#\"Transformar Arquivo\"(#\"Arquivo de Amostra\"))),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Coluna de Tabela Expandida1\",{{\"Nome da Origem\", type text}, {\"Filial\", Int64.Type}, {\"Data do Pedido\", type datetime}, {\"Tipo de pedido\", type text}, {\"Wave\", type text}, {\"Data locação pedido\", type datetime}, {\"Shipment\", Int64.Type}, {\"Filial Destino\", Int64.Type}, {\"Pedido\", Int64.Type}, {\"Status Pedido\", type text}, {\"Pedido de Venda\", type text}, {\"oLPN\", Int64.Type}, {\"Último Update oLPN\", type datetime}, {\"TOTE\", type text}, {\"Tarefa\", type text}, {\"Tarefa Status\", type text}, {\"Grupo de Tarefa\", type text}, {\"Item\", Int64.Type}, {\"Descrição\", type text}, {\"Local de Picking\", type text}, {\"Qtde. Peças Item\", Int64.Type}, {\"Volume\", type number}, {\"Status oLPN\", type text}, {\"Numero da Gaiola\", type any}, {\"BOX\", Int64.Type}, {\"Marcação de EAD\", type any}, {\"Data Prevista Entrega\", type date}, {\"Data Limite Expedição\", type date}, {\"Inventory Type ID\", Int64.Type}, {\"Cod Setor Item\", Int64.Type}, {\"Desc Setor Item\", type text}, {\"Audit Status\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"Nome da Origem\", \"Data do Pedido\"}),",
                "    #\"Dividir Coluna por Delimitador\" = Table.SplitColumn(#\"Colunas Removidas\", \"Tipo de pedido\", Splitter.SplitTextByDelimiter(\" \", QuoteStyle.Csv), {\"Tipo de pedido.1\", \"Tipo de pedido.2\", \"Tipo de pedido.3\", \"Tipo de pedido.4\", \"Tipo de pedido.5\", \"Tipo de pedido.6\"}),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Dividir Coluna por Delimitador\",{{\"Tipo de pedido.1\", type text}, {\"Tipo de pedido.2\", type text}, {\"Tipo de pedido.3\", type text}, {\"Tipo de pedido.4\", type text}, {\"Tipo de pedido.5\", type text}, {\"Tipo de pedido.6\", type text}}),",
                "    #\"Colunas Removidas1\" = Table.RemoveColumns(#\"Tipo Alterado1\",{\"Tipo de pedido.2\", \"Tipo de pedido.3\", \"Tipo de pedido.4\", \"Tipo de pedido.5\", \"Tipo de pedido.6\", \"Wave\", \"Shipment\", \"Filial Destino\", \"Status Pedido\", \"Pedido de Venda\", \"oLPN\", \"TOTE\", \"Tarefa\", \"Tarefa Status\", \"Grupo de Tarefa\", \"Numero da Gaiola\", \"Marcação de EAD\", \"Data Prevista Entrega\", \"Inventory Type ID\", \"Cod Setor Item\", \"Audit Status\"}),",
                "    #\"Tipo Alterado2\" = Table.TransformColumnTypes(#\"Colunas Removidas1\",{{\"Data locação pedido\", type date}, {\"Último Update oLPN\", type date}, {\"Data Limite Expedição\", type date}}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Tipo Alterado2\",{{\"Filial\", \"filial\"}, {\"Tipo de pedido.1\", \"tipo_pedido\"}, {\"Último Update oLPN\", \"data\"}, {\"Qtde. Peças Item\", \"qtd_pecas\"}, {\"Desc Setor Item\", \"setor\"}, {\"BOX\", \"box\"}, {\"Local de Picking\", \"local_de_picking\"}, {\"Data locação pedido\", \"data_locacao\"}, {\"Data Limite Expedição\", \"data_limite\"}}),",
                "    sep_setor = Table.AddColumn(#\"Colunas Renomeadas\", \"sep_setor\", each if [tipo_pedido] = \"S01\" or [tipo_pedido] = \"S04\" or [tipo_pedido] = \"S02\" then \"Entrega a Clientes\" ",
                "else if [tipo_pedido] = \"S05\" then \"EAD\" ",
                "else if [tipo_pedido] = \"S13\" and ([box] > 595 and [box] < 638) then \"EAD\"",
                "else if [tipo_pedido] = \"S14\" and ([box] > 595 and [box] < 638) then \"EAD\"",
                "else if [tipo_pedido] = \"S46\" and ([box] > 595 and [box] < 638) then \"EAD\"",
                "else if [tipo_pedido] = \"S53\" and ([box] > 595 and [box] < 638) then \"EAD\"",
                "else if [tipo_pedido] = \"S39\" or [tipo_pedido] = \"S39I\" or [tipo_pedido] = \"S39M\" or [tipo_pedido] = \"S39P\" or [tipo_pedido] = \"S39R\" then \"leves\"",
                "else if [tipo_pedido] = \"S13\" or [tipo_pedido] = \"S14\" or [tipo_pedido] = \"S46\" or [tipo_pedido] = \"S48\" then \"Abastecimento de lojas\"",
                "else if [tipo_pedido] = \"S53\" then \"Balanco\"",
                "else \"Ignorar\"),",
                "    salao_or_par = Table.AddColumn(sep_setor, \"salao_or_par\", each if [local_de_picking] = \"\" then \"Vazio\"",
                "else if Text.Start([local_de_picking], 2) = \"R0\" or",
                "        Text.Start([local_de_picking], 2) = \"P0\" or",
                "        Text.Start([local_de_picking], 2) = \"C0\" or",
                "        Text.Start([local_de_picking], 2) = \"S0\" or",
                "        Text.Start([local_de_picking], 2) = \"CP\" or",
                "        Text.Start([local_de_picking], 2) = \"CR\" or",
                "        Text.Start([local_de_picking], 7) = \"DIN-PAR\" or",
                "        Text.Start([local_de_picking], 2) = \"CS\" then \"par\"",
                "else \"salao\"),",
                "    #\"48hrs_24hrs\" = Table.AddColumn(salao_or_par, \"48hrs_24hrs\", each if [data_limite] <> null and [data_locacao] <> null and [data_limite] > [data_locacao] then \"48hrs\"",
                "else if [data_limite] <> null and [data_locacao] <> null and [data_limite] = [data_locacao] then \"24hrs\"",
                "else if [data_locacao] = null then null",
                "else null),",
                "    tipo_expedicao = Table.AddColumn(#\"48hrs_24hrs\", \"tipo_expedicao\", each if List.Contains({267,269,270,271,272,273,274,275},[box]) then \"crossdocking\"",
                "else if List.Contains({276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322},[box]) then \"polo\" else \"\"),",
                "    #\"Tipo Alterado3\" = Table.TransformColumnTypes(tipo_expedicao,{{\"sep_setor\", type text}, {\"salao_or_par\", type text}, {\"48hrs_24hrs\", type text}, {\"data_limite\", type date}, {\"data_locacao\", type date}, {\"data\", type date}, {\"tipo_expedicao\", type text}}),",
                "    #\"Consultas Mescladas\" = Table.NestedJoin(#\"Tipo Alterado3\", {\"Item\"}, dvalor_monetario, {\"sku\"}, \"dvalor_monetario\", JoinKind.LeftOuter),",
                "    #\"dvalor_monetario Expandido\" = Table.ExpandTableColumn(#\"Consultas Mescladas\", \"dvalor_monetario\", {\"valor_monetario\"}, {\"dvalor_monetario.valor_monetario\"}),",
                "    #\"Personalização Adicionada\" = Table.AddColumn(#\"dvalor_monetario Expandido\", \"valor_monetario\", each [qtd_pecas]*[dvalor_monetario.valor_monetario]),",
                "    #\"Colunas Removidas2\" = Table.RemoveColumns(#\"Personalização Adicionada\",{\"dvalor_monetario.valor_monetario\"}),",
                "    #\"Tipo Alterado4\" = Table.TransformColumnTypes(#\"Colunas Removidas2\",{{\"valor_monetario\", type number}}),",
                "    #\"Personalização Adicionada1\" = Table.AddColumn(#\"Tipo Alterado4\", \"setor_tratado\", each if List.Contains({\"CAMEBA\", \"CASA E CONSTRUCAO\", \"COPA E SALA DE JANTAR\", \"UTILIDADES DOMESTICAS\", \"WEARABLES\"}, [setor]) then \"CASA E CONSTRUÇÃO\"",
                "else if List.Contains({\"BRINQUEDOS/PEDAL\", \"DISNEY SUPER LOJA\", \"DVDS E BLU-RAY\"}, [setor]) then \"BRINQUEDOS\"",
                "else if List.Contains({\"BORAVAREJAR\", \"DECORACOES\", \"PAPELARIA\"}, [setor]) then \"DECORAÇÕES\"",
                "else if List.Contains({\"LAVADORAS\", \"QUEIMADORES\", \"REFRIGERACAO\", \"SAZONAIS PORTATEIS\", \"TVS\"}, [setor]) then \"ELETRODOMESTICOS\"",
                "else if List.Contains({\"ACESSORIOS E INOVACOES\", \"GAMES\", \"INFORMATICA\", \"PORTATEIS\", \"TABLETS\", \"TABLETS, IMPRESSAO E MONI\", \"TELEFONIA CELULAR\"}, [setor]) then \"ELETRONICOS\"",
                "else if List.Contains({\"COLCHOES\", \"ESTOFADOS\"}, [setor]) then \"ESTOFADOS\"",
                "else if List.Contains({\"MOVEIS DE COZINHA\", \"MOVEIS DE QUARTO\", \"MOVEIS INFANTIS\", \"MOVEIS PARA ESCRITORIO\", \"MOVEIS PLANEJADOS\", \"MOVEIS SALA DE ESTAR\"}, [setor]) then \"MOVEIS\"",
                "else if List.Contains({\"MALAS / MOCHILAS / ACESSO\", \"MODA\"}, [setor]) then \"TECIDOS\"",
                "else [setor]),",
                "    #\"Tipo Alterado5\" = Table.TransformColumnTypes(#\"Personalização Adicionada1\",{{\"setor_tratado\", type text}})",
                "in",
                "    #\"Tipo Alterado5\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fbase_online_pesados_abs_cancelamentos",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "filial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ba4dfaff-2c66-4272-8d21-3404196076e7",
            "sourceColumn": "filial",
            "summarizeBy": "sum"
          },
          {
            "name": "tipo_pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "95550f0c-bbbd-4e78-876b-a4f326791708",
            "sourceColumn": "tipo_pedido",
            "summarizeBy": "none"
          },
          {
            "name": "qtd_pecas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b6e3126a-f44f-4167-999c-db43251b6cbe",
            "sourceColumn": "qtd_pecas",
            "summarizeBy": "sum"
          },
          {
            "name": "data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "8d30391f-9aaa-4b30-ade7-d7b61ee3f8d3",
            "sourceColumn": "data",
            "summarizeBy": "none"
          },
          {
            "name": "user",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1b3465b8-7568-4c18-bbcd-068561796cc6",
            "sourceColumn": "user",
            "summarizeBy": "none"
          },
          {
            "name": "sep_setor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b7684ad8-3aad-4294-b738-b1f27be0eaa2",
            "sourceColumn": "sep_setor",
            "summarizeBy": "none"
          },
          {
            "name": "codigo_cancelamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02153f18-e5d3-4bc4-9761-ce70e1eed3c7",
            "sourceColumn": "codigo_cancelamento",
            "summarizeBy": "none"
          },
          {
            "name": "motivo_cancelamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd1c83fe-3252-4471-a2e2-f06622222095",
            "sourceColumn": "motivo_cancelamento",
            "summarizeBy": "none"
          },
          {
            "name": "item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bea521d1-7337-4f93-ab46-7df4871a2086",
            "sourceColumn": "item",
            "summarizeBy": "sum"
          },
          {
            "name": "valor_monetario",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ea6887da-6233-4dee-8fb7-1a6a5475c6d8",
            "sourceColumn": "valor_monetario",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "a8b99b21-7f36-401a-bcb5-8e6f31cd3dfe",
        "partitions": [
          {
            "name": "fbase_online_pesados_abs_cancelamentos",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = SharePoint.Contents(\"https://viavarejo.sharepoint.com/sites/grupo_de_dados_wave\", [ApiVersion = 15]),",
                "    #\"Atualizaes de Relatrios Gerais\" = Fonte{[Name=\"Atualizaes de Relatrios Gerais\"]}[Content],",
                "    #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\" = #\"Atualizaes de Relatrios Gerais\"{[Name=\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"]}[Content],",
                "    #\"Relatórios históricos\" = #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"{[Name=\"Relatórios históricos\"]}[Content],",
                "    #\"Painel de Navegacao Gerencial - ADMS - Vinicius &  Almeida\" = #\"Relatórios históricos\"{[Name=\"Painel de Navegacao Gerencial - ADMS - Vinicius &  Almeida\"]}[Content],",
                "    #\"SLA - Leves && Pesados && EAD\" = #\"Painel de Navegacao Gerencial - ADMS - Vinicius &  Almeida\"{[Name=\"SLA - Leves && Pesados && EAD\"]}[Content],",
                "    #\"Cancelamento All\" = #\"SLA - Leves && Pesados && EAD\"{[Name=\"Cancelamento All\"]}[Content],",
                "    #\"Arquivos Ocultos Filtrados1\" = Table.SelectRows(#\"Cancelamento All\", each [Attributes]?[Hidden]? <> true),",
                "    #\"Invocar Função Personalizada1\" = Table.AddColumn(#\"Arquivos Ocultos Filtrados1\", \"Transformar Arquivo (2)\", each #\"Transformar Arquivo (2)\"([Content])),",
                "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"Invocar Função Personalizada1\", {\"Name\", \"Nome da Origem\"}),",
                "    #\"Outras Colunas Removidas1\" = Table.SelectColumns(#\"Colunas Renomeadas1\", {\"Nome da Origem\", \"Transformar Arquivo (2)\"}),",
                "    #\"Coluna de Tabela Expandida1\" = Table.ExpandTableColumn(#\"Outras Colunas Removidas1\", \"Transformar Arquivo (2)\", Table.ColumnNames(#\"Transformar Arquivo (2)\"(#\"Arquivo de Amostra (2)\"))),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Coluna de Tabela Expandida1\",{{\"Nome da Origem\", type text}, {\"Filial\", Int64.Type}, {\"Inventory Type ID\", Int64.Type}, {\"Pedido\", type text}, {\"Pedido de Venda\", type text}, {\"Tipo da Ordem \", type text}, {\"Carga\", Int64.Type}, {\"Destinatário\", type any}, {\"item\", Int64.Type}, {\"Descrição do item\", type text}, {\"Qtde Original\", Int64.Type}, {\"Qtde Expedida\", Int64.Type}, {\"Qtde Ajustada\", Int64.Type}, {\"Data integração WMS\", type datetime}, {\"Data do Cancelamento\", type datetime}, {\"Usuário\", type text}, {\"Código Reference Text\", Int64.Type}, {\" Motivo Secondary Reference Text\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"Nome da Origem\", \"Inventory Type ID\", \"Pedido\", \"Pedido de Venda\", \"Carga\", \"Destinatário\", \"Descrição do item\", \"Qtde Original\", \"Qtde Expedida\", \"Data integração WMS\"}),",
                "    #\"Dividir Coluna por Delimitador\" = Table.SplitColumn(#\"Colunas Removidas\", \"Tipo da Ordem \", Splitter.SplitTextByDelimiter(\" \", QuoteStyle.Csv), {\"Tipo da Ordem .1\", \"Tipo da Ordem .2\"}),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Dividir Coluna por Delimitador\",{{\"Tipo da Ordem .1\", type text}, {\"Tipo da Ordem .2\", type text}}),",
                "    #\"Colunas Removidas1\" = Table.RemoveColumns(#\"Tipo Alterado1\",{\"Tipo da Ordem .2\"}),",
                "    #\"Data Extraída\" = Table.TransformColumns(#\"Colunas Removidas1\",{{\"Data do Cancelamento\", DateTime.Date, type date}}),",
                "    #\"Tipo Alterado2\" = Table.TransformColumnTypes(#\"Data Extraída\",{{\"Data do Cancelamento\", type date}}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Tipo Alterado2\",{{\"Tipo da Ordem .1\", \"tipo_pedido\"}, {\"Filial\", \"filial\"}, {\"Qtde Ajustada\", \"qtd_pecas\"}, {\"Data do Cancelamento\", \"data\"}, {\"Usuário\", \"user\"}, {\" Motivo Secondary Reference Text\", \"motivo_cancelamento\"}, {\"Código Reference Text\", \"codigo_cancelamento\"}}),",
                "    #\"Tipo Alterado5\" = Table.TransformColumnTypes(#\"Colunas Renomeadas\",{{\"codigo_cancelamento\", type text}}),",
                "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Tipo Alterado5\", \"sep_setor\", each if [tipo_pedido] = \"S01\" or [tipo_pedido] = \"S04\" then \"entrega a clientes\" ",
                "else if [tipo_pedido] = \"S05\"",
                " then \"EAD\" ",
                "else if [tipo_pedido] = \"S39\" or [tipo_pedido] = \"S39I\" or [tipo_pedido] = \"S39M\" or [tipo_pedido] = \"S39P\" or [tipo_pedido] = \"S39R\" then \"leves\"",
                "else if [tipo_pedido] = \"S13\" or [tipo_pedido] = \"S14\" or [tipo_pedido] = \"S46\" or [tipo_pedido] = \"S53\" or [tipo_pedido] = \"S48\" then \"Abastecimento de lojas\"",
                "else if [tipo_pedido] = \"S53\" then \"Balanco\"",
                "",
                "",
                "else \"Ignorar\"),",
                "    #\"Tipo Alterado3\" = Table.TransformColumnTypes(#\"Personalização Adicionada\",{{\"sep_setor\", type text}}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Tipo Alterado3\", each ([sep_setor] <> \"Ignorar\")),",
                "    #\"Personalização Adicionada1\" = Table.AddColumn(#\"Linhas Filtradas\", \"motivo_cancelamento.1\", each let",
                "    // Função para normalizar o texto (converter para maiúsculas e remover acentuação)",
                "    NormalizeText = (text as text) as text =>",
                "    let",
                "        // Converter texto para maiúsculas",
                "        NormalizedText = Text.Upper(text),",
                "        // Remover acentuação",
                "        RemoveAccents1 = Text.Replace(NormalizedText, \"Á\", \"A\"),",
                "        RemoveAccents2 = Text.Replace(RemoveAccents1, \"À\", \"A\"),",
                "        RemoveAccents3 = Text.Replace(RemoveAccents2, \"Â\", \"A\"),",
                "        RemoveAccents4 = Text.Replace(RemoveAccents3, \"Ã\", \"A\"),",
                "        RemoveAccents5 = Text.Replace(RemoveAccents4, \"É\", \"E\"),",
                "        RemoveAccents6 = Text.Replace(RemoveAccents5, \"Ê\", \"E\"),",
                "        RemoveAccents7 = Text.Replace(RemoveAccents6, \"Í\", \"I\"),",
                "        RemoveAccents8 = Text.Replace(RemoveAccents7, \"Ó\", \"O\"),",
                "        RemoveAccents9 = Text.Replace(RemoveAccents8, \"Ô\", \"O\"),",
                "        RemoveAccents10 = Text.Replace(RemoveAccents9, \"Õ\", \"O\"),",
                "        RemoveAccents11 = Text.Replace(RemoveAccents10, \"Ú\", \"U\"),",
                "        RemoveAccents12 = Text.Replace(RemoveAccents11, \"Ç\", \"C\")",
                "    in",
                "        RemoveAccents12,",
                "",
                "    // Função para verificar se o texto começa com a primeira palavra de cada motivo",
                "    StartsWithWord = (text as text, word as text) as logical =>",
                "    let",
                "        NormalizedText = NormalizeText(text),",
                "        NormalizedWord = NormalizeText(word),",
                "        StartsWith = Text.StartsWith(NormalizedText, NormalizedWord)",
                "    in",
                "        StartsWith,",
                "",
                "    // Normalizar o valor da coluna",
                "    NormalizedMotivo = NormalizeText([motivo_cancelamento]),",
                "",
                "    // Determinar o resultado com base no código e motivo",
                "    Result = ",
                "    if [codigo_cancelamento] = 1 or StartsWithWord([motivo_cancelamento], \"OUTROS\") then \"OUTROS\"",
                "    else if [codigo_cancelamento] = 2 or StartsWithWord([motivo_cancelamento], \"DIVERGÊNCIA\") then \"DIVERGÊNCIA DE SALDO PCOM X WMS\"",
                "    else if [codigo_cancelamento] = 3 or StartsWithWord([motivo_cancelamento], \"PENDÊNCIA\") then \"PENDÊNCIA DE ARMAZENAGEM\"",
                "    else if [codigo_cancelamento] = 4 or StartsWithWord([motivo_cancelamento], \"ENDEREÇO\") then \"ENDEREÇO VAZIO\"",
                "    else if [codigo_cancelamento] = 5 or StartsWithWord([motivo_cancelamento], \"NF\") then \"NF SEM TRATAMENTO\"",
                "    else if [codigo_cancelamento] = 6 or StartsWithWord([motivo_cancelamento], \"LEITURA\") then \"LEITURA IMEI\"",
                "    else if [codigo_cancelamento] = 7 or StartsWithWord([motivo_cancelamento], \"ERRO\") then \"ERRO OPERACIONAL\"",
                "    else if [codigo_cancelamento] = 8 or StartsWithWord([motivo_cancelamento], \"AVARIA\") then \"AVARIA\"",
                "    else if [codigo_cancelamento] = 9 or StartsWithWord([motivo_cancelamento], \"AVARIA/EAD\") then \"AVARIA/EAD\"",
                "    else if [codigo_cancelamento] = 10 or StartsWithWord([motivo_cancelamento], \"SALDO\") then \"SALDO INSUFICIENTE\"",
                "    else if [codigo_cancelamento] = 11 or StartsWithWord([motivo_cancelamento], \"FALTA\") then \"FALTA EAD\"",
                "    else if [codigo_cancelamento] = 12 or StartsWithWord([motivo_cancelamento], \"TRANSPORTADORA\") then \"TRANSPORTADORA DECLINADA\"",
                "    else if [codigo_cancelamento] = 13 or StartsWithWord([motivo_cancelamento], \"SKU\") then \"SKU DIVERGENTE\"",
                "    else if [codigo_cancelamento] = 14 or StartsWithWord([motivo_cancelamento], \"PROGRAMAÇÃO\") then \"PROGRAMAÇÃO INDEVIDA\"",
                "    else if [codigo_cancelamento] = 15 or StartsWithWord([motivo_cancelamento], \"ILPN\") then \"ILPN VOANDO\"",
                "    else if [codigo_cancelamento] = 16 or StartsWithWord([motivo_cancelamento], \"EXCESSO\") then \"EXCESSO DE CUBAGEM\"",
                "    else if [codigo_cancelamento] = 17 or StartsWithWord([motivo_cancelamento], \"DTF\") then \"DTF RETORNO\"",
                "    else if [codigo_cancelamento] = 18 or StartsWithWord([motivo_cancelamento], \"FALTA\") then \"FALTA DE COMPOSIÇÃO\"",
                "    else \"SEM MOTIVO\"",
                "in",
                "    Result),",
                "    #\"Colunas Removidas2\" = Table.RemoveColumns(#\"Personalização Adicionada1\",{\"motivo_cancelamento\"}),",
                "    #\"Colunas Renomeadas2\" = Table.RenameColumns(#\"Colunas Removidas2\",{{\"motivo_cancelamento.1\", \"motivo_cancelamento\"}}),",
                "    #\"Tipo Alterado4\" = Table.TransformColumnTypes(#\"Colunas Renomeadas2\",{{\"motivo_cancelamento\", type text}}),",
                "    #\"Erros Substituídos\" = Table.ReplaceErrorValues(#\"Tipo Alterado4\", {{\"codigo_cancelamento\", \"\"}}),",
                "    #\"Erros Substituídos1\" = Table.ReplaceErrorValues(#\"Erros Substituídos\", {{\"motivo_cancelamento\", \"\"}}),",
                "    #\"Consultas Mescladas\" = Table.NestedJoin(#\"Erros Substituídos1\", {\"item\"}, dvalor_monetario, {\"sku\"}, \"dvalor_monetario\", JoinKind.LeftOuter),",
                "    #\"dvalor_monetario Expandido\" = Table.ExpandTableColumn(#\"Consultas Mescladas\", \"dvalor_monetario\", {\"valor_monetario\"}, {\"dvalor_monetario.valor_monetario\"}),",
                "    #\"Personalização Adicionada2\" = Table.AddColumn(#\"dvalor_monetario Expandido\", \"valor_monetario\", each [qtd_pecas]*[dvalor_monetario.valor_monetario]),",
                "    #\"Tipo Alterado6\" = Table.TransformColumnTypes(#\"Personalização Adicionada2\",{{\"valor_monetario\", type number}}),",
                "    #\"Colunas Removidas3\" = Table.RemoveColumns(#\"Tipo Alterado6\",{\"dvalor_monetario.valor_monetario\"})",
                "in",
                "    #\"Colunas Removidas3\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dcalendario",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "calendario",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "6ba434b9-983d-4cff-b374-2663f545a55d",
            "sourceColumn": "calendario",
            "summarizeBy": "none"
          },
          {
            "name": "ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1197f072-7ea8-4495-b3ef-f6fe6dec7680",
            "sourceColumn": "ano",
            "summarizeBy": "sum"
          },
          {
            "name": "mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "25d75c59-c658-4234-9f42-b803bf79a407",
            "sourceColumn": "mes",
            "summarizeBy": "none"
          },
          {
            "name": "nome_mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "ca9aef72-a781-4ede-a748-af78187cc3a5",
            "sortByColumn": "mes",
            "sourceColumn": "nome_mes",
            "summarizeBy": "none"
          },
          {
            "name": "dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b59f2c62-4d72-44da-b052-259ab536007b",
            "sourceColumn": "dia",
            "summarizeBy": "none"
          },
          {
            "name": "nome_dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6947bede-cc0f-432a-ba96-37cdb85edc2b",
            "sourceColumn": "nome_dia",
            "summarizeBy": "none"
          },
          {
            "name": "periodos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8bdd6d52-7c8d-4490-8e76-2c8b4ec52dd3",
            "sourceColumn": "periodos",
            "summarizeBy": "none"
          },
          {
            "name": "semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d05ddd94-a3f3-42e8-8d10-d36f91fabe66",
            "sourceColumn": "semana",
            "summarizeBy": "sum"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "2e7e7449-675a-4349-96ee-221720f731c7",
        "partitions": [
          {
            "name": "dcalendario",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Consulta1(#date(2023, 1, 1), 3650, #duration(1, 0, 0, 0)),",
                "    #\"Convertido para Tabela\" = Table.FromList(Fonte, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Convertido para Tabela\",{{\"Column1\", \"data\"}}),",
                "    #\"Ano Inserido\" = Table.AddColumn(#\"Colunas Renomeadas\", \"Ano\", each Date.Year([data]), Int64.Type),",
                "    #\"Mês Inserido\" = Table.AddColumn(#\"Ano Inserido\", \"Mês\", each Date.Month([data]), Int64.Type),",
                "    #\"Nome do Mês Inserido\" = Table.AddColumn(#\"Mês Inserido\", \"Nome do Mês\", each Date.MonthName([data]), type text),",
                "    #\"Dia Inserido\" = Table.AddColumn(#\"Nome do Mês Inserido\", \"Dia\", each Date.Day([data]), Int64.Type),",
                "    #\"Nome do Dia Inserido\" = Table.AddColumn(#\"Dia Inserido\", \"Nome do Dia\", each Date.DayOfWeekName([data]), type text),",
                "    #\"Semana do Mês Inserida\" = Table.AddColumn(#\"Nome do Dia Inserido\", \"Semana do Mês\", each Date.WeekOfMonth([data]), Int64.Type),",
                "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"Semana do Mês Inserida\",{{\"data\", \"calendario\"}, {\"Ano\", \"ano\"}, {\"Mês\", \"mes\"}, {\"Nome do Mês\", \"nome_mes\"}, {\"Dia\", \"dia\"}, {\"Nome do Dia\", \"nome_dia\"}, {\"Semana do Mês\", \"semana\"}}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Colunas Renomeadas1\",{{\"calendario\", type date}}),",
                "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Tipo Alterado\", \"periodos\", each if [calendario] >= #date(2023, 10,1) and [calendario] <= #date(2023,11,30) then \"Black 2023\"",
                "else if [calendario] >= #date(2024, 10,1) and [calendario] <= #date(2024,11,30) then \"Black 2024\"",
                "else null),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Personalização Adicionada\",{{\"periodos\", type text}})",
                "in",
                "    #\"Tipo Alterado1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fbase_abastecimento_demanda",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "22c8301e-260b-4311-b2b8-03272116f16a",
            "sourceColumn": "data",
            "summarizeBy": "none"
          },
          {
            "name": "demanda",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3331b182-3c5a-4201-bffc-60f62133e36d",
            "sourceColumn": "demanda",
            "summarizeBy": "sum"
          },
          {
            "name": "balanco",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "356a9746-6596-4326-b4bf-a7952030aef4",
            "sourceColumn": "balanco",
            "summarizeBy": "sum"
          },
          {
            "name": "rejeitados_pcp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9bb8d8f0-2c92-4b5a-8d6a-14a6f15d1d4c",
            "sourceColumn": "rejeitados_pcp",
            "summarizeBy": "sum"
          },
          {
            "name": "rejeitados_dec",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4491d82b-c111-438f-bf0f-d6f1b76995a9",
            "sourceColumn": "rejeitados_dec",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "bac877cb-1d33-49dc-9dd2-779a5b2d0365",
        "partitions": [
          {
            "name": "fbase_abastecimento_demanda",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = SharePoint.Contents(\"https://viavarejo.sharepoint.com/sites/grupo_de_dados_wave\", [ApiVersion = 15]),",
                "    #\"Atualizaes de Relatrios Gerais\" = Fonte{[Name=\"Atualizaes de Relatrios Gerais\"]}[Content],",
                "    #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\" = #\"Atualizaes de Relatrios Gerais\"{[Name=\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"]}[Content],",
                "    #\"Relatórios históricos\" = #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"{[Name=\"Relatórios históricos\"]}[Content],",
                "    #\"Painel de Navegacao Gerencial - ADMS - Vinicius &  Almeida\" = #\"Relatórios históricos\"{[Name=\"Painel de Navegacao Gerencial - ADMS - Vinicius &  Almeida\"]}[Content],",
                "    #\"SLA - Abastecimento de Lojas\" = #\"Painel de Navegacao Gerencial - ADMS - Vinicius &  Almeida\"{[Name=\"SLA - Abastecimento de Lojas\"]}[Content],",
                "    #\"evolucao_diarizada xlsx\" = #\"SLA - Abastecimento de Lojas\"{[Name=\"evolucao_diarizada.xlsx\"]}[Content],",
                "    #\"Pasta de Trabalho Importada do Excel\" = Excel.Workbook(#\"evolucao_diarizada xlsx\"),",
                "    Tabela1_Table = #\"Pasta de Trabalho Importada do Excel\"{[Item=\"Tabela1\",Kind=\"Table\"]}[Data],",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Tabela1_Table,{{\"data\", type date}, {\"balanco\", Int64.Type}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fbase_abastecimento_cancelamentos",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "e4f041a6-9882-4b7a-ad66-f70bb368b99b",
            "sourceColumn": "data",
            "summarizeBy": "none"
          },
          {
            "name": "responsavel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "75c809df-c33b-4c16-8a14-4482ed0a4343",
            "sourceColumn": "responsavel",
            "summarizeBy": "none"
          },
          {
            "name": "motivo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "640c4536-f53b-47cc-a5d9-75c1c76b9a8e",
            "sourceColumn": "motivo",
            "summarizeBy": "none"
          },
          {
            "name": "quantidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "80456cbc-c2ad-4ad7-a2b6-da81874586ce",
            "sourceColumn": "quantidade",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "2ac0c836-c091-405c-b1c3-c2d185419e58",
        "partitions": [
          {
            "name": "fbase_abastecimento_cancelamentos",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = SharePoint.Contents(\"https://viavarejo.sharepoint.com/sites/grupo_de_dados_wave\", [ApiVersion = 15]),",
                "    #\"Atualizaes de Relatrios Gerais\" = Fonte{[Name=\"Atualizaes de Relatrios Gerais\"]}[Content],",
                "    #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\" = #\"Atualizaes de Relatrios Gerais\"{[Name=\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"]}[Content],",
                "    #\"Relatórios históricos\" = #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"{[Name=\"Relatórios históricos\"]}[Content],",
                "    #\"Painel de Navegacao Gerencial - ADMS - Vinicius &  Almeida\" = #\"Relatórios históricos\"{[Name=\"Painel de Navegacao Gerencial - ADMS - Vinicius &  Almeida\"]}[Content],",
                "    #\"SLA - Abastecimento de Lojas\" = #\"Painel de Navegacao Gerencial - ADMS - Vinicius &  Almeida\"{[Name=\"SLA - Abastecimento de Lojas\"]}[Content],",
                "    #\"evolucao_diarizada xlsx\" = #\"SLA - Abastecimento de Lojas\"{[Name=\"evolucao_diarizada.xlsx\"]}[Content],",
                "    #\"Pasta de Trabalho Importada do Excel\" = Excel.Workbook(#\"evolucao_diarizada xlsx\"),",
                "    Tabela13_Table = #\"Pasta de Trabalho Importada do Excel\"{[Item=\"Tabela13\",Kind=\"Table\"]}[Data],",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Tabela13_Table,{{\"data\", type date}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dsetor",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "sep_setor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b714a66c-5215-4b5c-9d84-a1ce7b00c72a",
            "sourceColumn": "sep_setor",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "6d47fd8a-81db-42f0-88c7-d36757dd0c1d",
        "partitions": [
          {
            "name": "dsetor",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WcnV0UYrViVZKzSspSk1PVEhUSM7JBHJSwaI5qWWpxUqxsQA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [sep_setor = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"sep_setor\", type text}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fbase_hc_abastecimento",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "dec510e1-0f8e-4a40-b64f-b6c06dd557ac",
            "sourceColumn": "data",
            "summarizeBy": "none"
          },
          {
            "name": "chip_48h",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "3c5751e4-61af-47f2-954a-4e001eef83ee",
            "sourceColumn": "chip_48h",
            "summarizeBy": "sum"
          },
          {
            "name": "carros_sp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "8fcdf47a-2a6a-4838-9107-9a671a0265a9",
            "sourceColumn": "carros_sp",
            "summarizeBy": "sum"
          },
          {
            "name": "chip_cross_polo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "9b001bae-6ccc-43c7-8a43-21e8426359ca",
            "sourceColumn": "chip_cross_polo",
            "summarizeBy": "sum"
          },
          {
            "name": "polo_carretas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "9350e446-1319-46b6-a5c6-22aff60f5285",
            "sourceColumn": "polo_carretas",
            "summarizeBy": "sum"
          },
          {
            "name": "carro_balanco",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "728498d4-2256-48c2-927b-8300095bbad6",
            "sourceColumn": "carro_balanco",
            "summarizeBy": "sum"
          },
          {
            "name": "hc_1_turno_salao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "6d2686a8-4890-4fd1-a200-8f1101328bd8",
            "sourceColumn": "hc_1_turno_salao",
            "summarizeBy": "sum"
          },
          {
            "name": "hc_1_turno_par",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "c33a6a8a-1552-4712-9b89-1ff6b8357784",
            "sourceColumn": "hc_1_turno_par",
            "summarizeBy": "sum"
          },
          {
            "name": "hc_1_turno_fast",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "9328e563-8772-4594-aaf5-36134f40fbb2",
            "sourceColumn": "hc_1_turno_fast",
            "summarizeBy": "sum"
          },
          {
            "name": "hc_2_turno_salao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "8e15b81f-73ba-4619-90a5-fccd4114d97e",
            "sourceColumn": "hc_2_turno_salao",
            "summarizeBy": "sum"
          },
          {
            "name": "hc_2_turno_par",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "a5d97870-0b8f-4f4c-9a4e-277ab1891106",
            "sourceColumn": "hc_2_turno_par",
            "summarizeBy": "sum"
          },
          {
            "name": "hc_2_turno_fast",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "0755fa58-fbdc-4afe-b4ed-568a5b959217",
            "sourceColumn": "hc_2_turno_fast",
            "summarizeBy": "sum"
          },
          {
            "name": "hc_turno_3_salao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "0d6df92c-4d82-4847-b75b-e09f5584cf6f",
            "sourceColumn": "hc_turno_3_salao",
            "summarizeBy": "sum"
          },
          {
            "name": "hc_3_turno_fast",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "4d4a987d-246d-43ba-8cc4-6ce7b365e9bc",
            "sourceColumn": "hc_3_turno_fast",
            "summarizeBy": "sum"
          },
          {
            "name": "hc_3_turno_par",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "4b169450-aaf0-4bf9-bf0d-b316880f3d8e",
            "sourceColumn": "hc_3_turno_par",
            "summarizeBy": "sum"
          },
          {
            "name": "chip_geral",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "349060b7-cf91-48a0-a59f-6e9f9a6cb89a",
            "sourceColumn": "chip_geral",
            "summarizeBy": "sum"
          },
          {
            "name": "filiais",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3bc85028-bbb8-490e-83fd-82d93e771a08",
            "sourceColumn": "filiais",
            "summarizeBy": "sum"
          },
          {
            "name": "chip_24h",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6e7f6a0d-4ece-49f9-837b-ad40cffcc4c9",
            "sourceColumn": "chip_24h",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "231b23e4-3c34-430d-87a1-6e4b22d5ea82",
        "partitions": [
          {
            "name": "fbase_hc_abastecimento",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = SharePoint.Contents(\"https://viavarejo.sharepoint.com/sites/grupo_de_dados_wave\", [ApiVersion = 15]),",
                "    #\"Atualizaes de Relatrios Gerais\" = Fonte{[Name=\"Atualizaes de Relatrios Gerais\"]}[Content],",
                "    #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\" = #\"Atualizaes de Relatrios Gerais\"{[Name=\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"]}[Content],",
                "    #\"Relatórios históricos\" = #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"{[Name=\"Relatórios históricos\"]}[Content],",
                "    #\"Painel de Navegacao Gerencial - ADMS - Vinicius &  Almeida\" = #\"Relatórios históricos\"{[Name=\"Painel de Navegacao Gerencial - ADMS - Vinicius &  Almeida\"]}[Content],",
                "    #\"SLA - Abastecimento de Lojas\" = #\"Painel de Navegacao Gerencial - ADMS - Vinicius &  Almeida\"{[Name=\"SLA - Abastecimento de Lojas\"]}[Content],",
                "    #\"HC Abastecimento de Lojas - ADMs - Vinicius & Emerson xlsx\" = #\"SLA - Abastecimento de Lojas\"{[Name=\"HC Abastecimento de Lojas - ADMs - Vinicius & Emerson.xlsx\"]}[Content],",
                "    #\"Pasta de Trabalho Importada do Excel\" = Excel.Workbook(#\"HC Abastecimento de Lojas - ADMs - Vinicius & Emerson xlsx\"),",
                "    base_Table = #\"Pasta de Trabalho Importada do Excel\"{[Item=\"base\",Kind=\"Table\"]}[Data],",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(base_Table,{\"DATA ENTREGA\", \"48H0QTDE PEÇAS SALÃO SP\", \"48H0QTDE PEÇAS PAR SP\", \"QTDE ITENS SALÃO SP\", \"QTDE ITENS PAR SP\", \"CUBAGEM SALÃO SP\", \"CUBAGEM PAR SP\", \"QTDE BOX SP\", \"CROSS/POLO SALÃO\", \"CROSS/POLO PAR\", \"BALANÇO PAR\", \"INCLUSÃO 24H0SALÃO SP\", \"INCLUSÃO 24H0PAR SP\", \"INCLUSÃO CROSS0SALÃO\", \"INCLUSÃO CROSS0PAR\", \"DEMANDA TOTAL 0 SALÃO\", \"DEMANDA TOTAL 0 PAR\", \"DEMANDA TOTAL 0 GERAL\"}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Colunas Removidas\",{{\"DATA PICKING\", \"data\"}, {\"QTDE CHIP GERAL\", \"chip_geral\"}, {\"CHIP 48H SP\", \"chip_48h\"}, {\"QTDE CARRO SP\", \"carros_sp\"}, {\"QTDE FILIAIS SP\", \"filiais\"}, {\"CHIP CROSS/POLO\", \"chip_cross_polo\"}, {\"QTDE POLO/CARRETAS\", \"polo_carretas\"}, {\"CARROS 0 BALANÇO\", \"carro_balanco\"}, {\"CHIP 24H SP\", \"chip_24h\"}, {\"HC 1ºTURNO 0 SALÃO\", \"hc_1_turno_salao\"}, {\"HC 1ºTURNO 0 PAR\", \"hc_1_turno_par\"}, {\"HC FAST LOG 1ºT\", \"hc_1_turno_fast\"}, {\"HC 2ºTURNO 0 SALÃO\", \"hc_2_turno_salao\"}, {\"HC 2ºTURNO 0 PAR\", \"hc_2_turno_par\"}, {\"HC FAST LOG 2ºT\", \"hc_2_turno_fast\"}, {\"HC 3ºTURNO 0 SALÃO\", \"hc_turno_3_salao\"}, {\"HC FAST LOG 3ºT\", \"hc_3_turno_fast\"}, {\"HC 3ºTURNO 0 PAR\", \"hc_3_turno_par\"}}),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"Colunas Renomeadas\",null,0,Replacer.ReplaceValue,{\"chip_geral\", \"chip_48h\", \"carros_sp\", \"filiais\", \"chip_cross_polo\", \"polo_carretas\", \"carro_balanco\", \"chip_24h\", \"hc_1_turno_salao\", \"hc_1_turno_par\", \"hc_1_turno_fast\", \"hc_2_turno_salao\", \"hc_2_turno_par\", \"hc_2_turno_fast\", \"hc_turno_3_salao\", \"hc_3_turno_fast\", \"hc_3_turno_par\"}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Valor Substituído\",{{\"chip_geral\", Int64.Type}, {\"chip_48h\", Int64.Type}, {\"carros_sp\", Int64.Type}, {\"filiais\", Int64.Type}, {\"chip_cross_polo\", Int64.Type}, {\"polo_carretas\", Int64.Type}, {\"carro_balanco\", Int64.Type}, {\"chip_24h\", Int64.Type}, {\"hc_1_turno_salao\", Int64.Type}, {\"hc_1_turno_par\", Int64.Type}, {\"hc_1_turno_fast\", Int64.Type}, {\"hc_2_turno_salao\", Int64.Type}, {\"hc_2_turno_par\", Int64.Type}, {\"hc_2_turno_fast\", Int64.Type}, {\"hc_turno_3_salao\", Int64.Type}, {\"hc_3_turno_fast\", Int64.Type}, {\"hc_3_turno_par\", Int64.Type}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fbase_expedicoes_abs",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "6b584905-3a4a-4a4d-87b2-c3e1867ff875",
            "sourceColumn": "data",
            "summarizeBy": "none"
          },
          {
            "name": "polo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ec73a9d2-303b-4f73-b1ac-f897ee9a7934",
            "sourceColumn": "polo",
            "summarizeBy": "sum"
          },
          {
            "name": "crossdocking",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e47a8d05-355c-4209-a4a0-e936d42ea3f0",
            "sourceColumn": "crossdocking",
            "summarizeBy": "sum"
          },
          {
            "name": "24hrs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3654b56e-b524-4265-9116-28cd5797a980",
            "sourceColumn": "24hrs",
            "summarizeBy": "sum"
          },
          {
            "name": "48hrs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f7c15f79-509a-49b3-8a05-a347aa3f6c3a",
            "sourceColumn": "48hrs",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "58965390-06ff-42b0-ad81-1148eb5848d1",
        "partitions": [
          {
            "name": "fbase_expedicoes_abs",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = SharePoint.Contents(\"https://viavarejo.sharepoint.com/sites/grupo_de_dados_wave\", [ApiVersion = 15]),",
                "    #\"Atualizaes de Relatrios Gerais\" = Fonte{[Name=\"Atualizaes de Relatrios Gerais\"]}[Content],",
                "    #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\" = #\"Atualizaes de Relatrios Gerais\"{[Name=\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"]}[Content],",
                "    #\"Relatórios históricos\" = #\"Relatórios dinâmicos - ADMs - Vinicius & Almeida\"{[Name=\"Relatórios históricos\"]}[Content],",
                "    #\"Painel de Navegacao Gerencial - ADMS - Vinicius &  Almeida\" = #\"Relatórios históricos\"{[Name=\"Painel de Navegacao Gerencial - ADMS - Vinicius &  Almeida\"]}[Content],",
                "    #\"SLA - Abastecimento de Lojas\" = #\"Painel de Navegacao Gerencial - ADMS - Vinicius &  Almeida\"{[Name=\"SLA - Abastecimento de Lojas\"]}[Content],",
                "    #\"demanda_por_expedicao xlsx\" = #\"SLA - Abastecimento de Lojas\"{[Name=\"demanda_por_expedicao.xlsx\"]}[Content],",
                "    #\"Pasta de Trabalho Importada do Excel\" = Excel.Workbook(#\"demanda_por_expedicao xlsx\"),",
                "    Tabela1_Table = #\"Pasta de Trabalho Importada do Excel\"{[Item=\"Tabela1\",Kind=\"Table\"]}[Data],",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(Tabela1_Table,{\"Demanda\", \"Nome do Mês\"}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Colunas Removidas\",{{\"Data\", \"data\"}, {\"Polo\", \"polo\"}, {\"Crossdocking\", \"crossdocking\"}, {\"Demanda 24 Horas\", \"24hrs\"}, {\"Demanda 48 Horas \", \"48hrs\"}}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Colunas Renomeadas\",{{\"data\", type date}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dhora",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "hora",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "a9a0a382-1bce-4fa0-9139-ae0a59813293",
            "sourceColumn": "hora",
            "summarizeBy": "none"
          },
          {
            "name": "hora_num",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a676ac1c-05d8-43c2-b9c6-0b50fb2e46de",
            "sourceColumn": "hora_num",
            "summarizeBy": "sum"
          },
          {
            "name": "minuto_num",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "94406f59-4c61-4afa-b193-74c73c534b40",
            "sourceColumn": "minuto_num",
            "summarizeBy": "sum"
          },
          {
            "name": "segundo_num",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "daf45d7c-422b-4526-aa83-aa31363ffd47",
            "sourceColumn": "segundo_num",
            "summarizeBy": "sum"
          },
          {
            "name": "am_pm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "94d0996b-ee47-4eb7-aae1-80c0ddbcc7d3",
            "sourceColumn": "am_pm",
            "summarizeBy": "none"
          },
          {
            "name": "turno",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "99c7716a-e6ca-413b-b754-6aca345c8179",
            "sourceColumn": "turno",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "3e8ad17a-5c83-4333-b9a4-28c6f86569ac",
        "partitions": [
          {
            "name": "dhora",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Lista = {0..86399},",
                "    ConverteParaTabela = Table.FromList(Lista, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    AlteraTipo = Table.TransformColumnTypes(ConverteParaTabela,{{\"Column1\", Int64.Type}}),",
                "    AlteraNomeCol = Table.RenameColumns(AlteraTipo,{{\"Column1\",\"Segundo\"}}),",
                "    ColDuracao = Table.AddColumn(AlteraNomeCol,\"Duração\", each #duration(0,0,0,[Segundo]), type duration),",
                "    ColHora = Table.AddColumn(ColDuracao,\"Hora\", each #time(Duration.Hours([Duração]),Duration.Minutes([Duração]),Duration.Seconds([Duração]))),",
                "    RemoveCols = Table.RemoveColumns(ColHora,{\"Duração\",\"Segundo\"}),",
                "    CollHoraNum = Table.AddColumn(RemoveCols, \"Hora Num\", each Time.Hour([Hora]), Int64.Type),",
                "    ColMinutoNum = Table.AddColumn(CollHoraNum,\"Minuto Num\", each Time.Minute([Hora]), Int64.Type),",
                "    ColSegundoNum = Table.AddColumn(ColMinutoNum,\"Segundo Num\", each Time.Second([Hora]), Int64.Type),",
                "    ColAMPM = Table.AddColumn(ColSegundoNum, \"AMPM\", each if [Hora Num] < 12 then \"AM\" else \"PM\", type text),",
                "    #\"Personalização Adicionada\" = Table.AddColumn(ColAMPM, \"ColTurno\", each if [Hora] >= #time(6, 0, 0) and [Hora] <= #time(14, 20, 59) then \"1º Turno\"",
                "else if [Hora] >= #time(14, 21, 0) and [Hora] <= #time(22, 41, 59) then \"2º Turno\" ",
                "else \"3º Turno\"),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Personalização Adicionada\",{{\"Hora\", type time}, {\"ColTurno\", type text}}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Tipo Alterado\",{{\"Hora\", \"hora\"}, {\"Hora Num\", \"hora_num\"}, {\"Minuto Num\", \"minuto_num\"}, {\"Segundo Num\", \"segundo_num\"}, {\"AMPM\", \"am_pm\"}, {\"ColTurno\", \"turno\"}})",
                "in",
                "    #\"Colunas Renomeadas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dzona",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "local",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dfd21488-dfa7-48b1-8e52-71884bae5748",
            "sourceColumn": "local",
            "summarizeBy": "none"
          },
          {
            "name": "zona",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1e8517c-c6d2-4182-9e55-9c9f875c55f2",
            "sourceColumn": "zona",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "3399f44b-2e96-407d-9341-15a9d4dd50be",
        "partitions": [
          {
            "name": "dzona",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = SharePoint.Contents(\"https://viavarejo.sharepoint.com/sites/grupo_de_dados_wave\", [ApiVersion = 15]),",
                "    #\"Atualizaes de Relatrios Gerais\" = Fonte{[Name=\"Atualizaes de Relatrios Gerais\"]}[Content],",
                "    #\"Relatórios estáticos - ADMs - Vinicius & Almeida\" = #\"Atualizaes de Relatrios Gerais\"{[Name=\"Relatórios estáticos - ADMs - Vinicius & Almeida\"]}[Content],",
                "    #\"Painel de Navegacao Gerencial - ADMS - Vinicius & Almeida\" = #\"Relatórios estáticos - ADMs - Vinicius & Almeida\"{[Name=\"Painel de Navegacao Gerencial - ADMS - Vinicius & Almeida\"]}[Content],",
                "    #\"local_zona xlsx\" = #\"Painel de Navegacao Gerencial - ADMS - Vinicius & Almeida\"{[Name=\"local_zona.xlsx\"]}[Content],",
                "    #\"Pasta de Trabalho Importada do Excel\" = Excel.Workbook(#\"local_zona xlsx\"),",
                "    local_zona_Sheet = #\"Pasta de Trabalho Importada do Excel\"{[Item=\"local_zona\",Kind=\"Sheet\"]}[Data],",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(local_zona_Sheet, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"local\", type text}, {\"zona\", type text}}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Tipo Alterado\", {\"local\"}),",
                "    #\"Duplicatas Removidas1\" = Table.Distinct(#\"Duplicatas Removidas\", {\"local\"}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Duplicatas Removidas1\", each [local] <> null and [local] <> \"\")",
                "in",
                "    #\"Linhas Filtradas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dbox",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "box",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1183865b-2f84-41f7-9fa3-9b120317384a",
            "sourceColumn": "box",
            "summarizeBy": "none"
          },
          {
            "name": "porta",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0aab5a80-4615-4bf8-84e4-118027dc660f",
            "sourceColumn": "porta",
            "summarizeBy": "none"
          },
          {
            "name": "setor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fbd6c405-8147-4d87-b203-a51feef19ee3",
            "sourceColumn": "setor",
            "summarizeBy": "none"
          },
          {
            "name": "desc.1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "90001681-cb3e-4a37-8ec6-b73d9da20759",
            "sourceColumn": "desc.1",
            "summarizeBy": "none"
          },
          {
            "name": "cubage_m3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "72ec182b-b32f-4ee0-81da-04ddc4fed6d9",
            "sourceColumn": "cubage_m3",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "813294ed-458d-45c1-b6cf-73cc7ea7696c",
        "partitions": [
          {
            "name": "dbox",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = SharePoint.Contents(\"https://viavarejo.sharepoint.com/sites/grupo_de_dados_wave\", [ApiVersion = 15]),",
                "    #\"Atualizaes de Relatrios Gerais\" = Fonte{[Name=\"Atualizaes de Relatrios Gerais\"]}[Content],",
                "    #\"Relatórios estáticos - ADMs - Vinicius & Almeida\" = #\"Atualizaes de Relatrios Gerais\"{[Name=\"Relatórios estáticos - ADMs - Vinicius & Almeida\"]}[Content],",
                "    #\"Painel de Navegacao Gerencial - ADMS - Vinicius & Almeida\" = #\"Relatórios estáticos - ADMs - Vinicius & Almeida\"{[Name=\"Painel de Navegacao Gerencial - ADMS - Vinicius & Almeida\"]}[Content],",
                "    #\"box xlsx\" = #\"Painel de Navegacao Gerencial - ADMS - Vinicius & Almeida\"{[Name=\"box.xlsx\"]}[Content],",
                "    #\"Pasta de Trabalho Importada do Excel\" = Excel.Workbook(#\"box xlsx\"),",
                "    box_Sheet = #\"Pasta de Trabalho Importada do Excel\"{[Item=\"box\",Kind=\"Sheet\"]}[Data],",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(box_Sheet, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"box\", Int64.Type}, {\"porta\", Int64.Type}, {\"setor\", type text}, {\"desc.1\", type text}, {\"cubage_m3\", Int64.Type}, {\"Column6\", type any}, {\"Column7\", type any}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"Column6\", \"Column7\"}),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Colunas Removidas\",{{\"box\", type text}}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Tipo Alterado1\", {\"box\"}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Duplicatas Removidas\", each [box] <> null and [box] <> \"\")",
                "in",
                "    #\"Linhas Filtradas\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}